# Python builder script for Day 49
import sys
from pathlib import Path

# Day jump options string with all 180 days
DAY_JUMP = """<option value="">Choose a day…</option>
<optgroup label="Foundations">
<option value="day-001.html">Day 1: Local workspace and learning baseline</option>
<option value="day-002.html">Day 2: IP addressing and packet paths</option>
<option value="day-003.html">Day 3: DNS, sockets and transport</option>
<option value="day-004.html">Day 4: TLS, HTTP, MTU and routing vocabulary</option>
<option value="day-005.html">Day 5: VPN, load balancers and firewalls</option>
<option value="day-006.html">Day 6: Shell, processes and services</option>
<option value="day-007.html">Day 7: SSH, scripts and process inspection</option>
<option value="day-008.html">Day 8: CPU, memory and diagnostic signals</option>
<option value="day-009.html">Day 9: VM and container isolation</option>
<option value="day-010.html">Day 10: Images, filesystems and orchestration</option>
<option value="day-011.html">Day 11: Cloud service models and shared responsibility</option>
<option value="day-012.html">Day 12: Resource hierarchy and inheritance</option>
<option value="day-013.html">Day 13: Cloud Identity, accounts and directory sync</option>
<option value="day-014.html">Day 14: IAM principals, roles and bindings</option>
<option value="day-015.html">Day 15: Service accounts, keys and delegation</option>
<option value="day-016.html">Day 16: Billing accounts, budgets and cost attribution</option>
<option value="day-017.html">Day 17: Gate 1 review: Foundations and identity</option>
</optgroup>
<optgroup label="Governance, network and security">
<option value="day-018.html">Day 18: Organization policies and constraints</option>
<option value="day-019.html">Day 19: Custom roles and least-privilege analysis</option>
<option value="day-020.html">Day 20: Audit logs, Access Transparency and admin tracking</option>
<option value="day-021.html">Day 21: VPC design, subnets and private IP spaces</option>
<option value="day-022.html">Day 22: Hierarchical and VPC firewall policy rules</option>
<option value="day-023.html">Day 23: Cloud NAT, Cloud Router and dynamic routing</option>
<option value="day-024.html">Day 24: Private Google Access and PSC fundamentals</option>
<option value="day-025.html">Day 25: Cloud DNS zones, routing and DNSSEC</option>
<option value="day-026.html">Day 26: Cloud Armor policies and DDoS mitigation</option>
<option value="day-027.html">Day 27: Cloud KMS, CMEK and envelope encryption</option>
<option value="day-028.html">Day 28: Secret Manager and runtime injection</option>
<option value="day-029.html">Day 29: Workload Identity Federation</option>
<option value="day-030.html">Day 30: VPC Service Controls perimeter design</option>
<option value="day-031.html">Day 31: VPC SC troubleshooting and ingress/egress rules</option>
<option value="day-032.html">Day 32: Security Command Center and threat posture</option>
<option value="day-033.html">Day 33: Cloud Monitoring workspace and alert policies</option>
<option value="day-034.html">Day 34: Cloud Logging sinks, storage and exports</option>
<option value="day-035.html">Day 35: Gate 2 review: Governance and security</option>
</optgroup>
<optgroup label="Compute, storage and databases">
<option value="day-036.html">Day 36: Compute Engine sizing, vCPU and memory models</option>
<option value="day-037.html">Day 37: Persistent disks, Hyperdisk, snapshots and IOPS</option>
<option value="day-038.html">Day 38: Managed instance groups and autoscaling algorithms</option>
<option value="day-039.html">Day 39: VM rolling updates, instance templates and health checks</option>
<option value="day-040.html">Day 40: Spot VMs, sole-tenant nodes and reservations</option>
<option value="day-041.html">Day 41: VM Manager, OS login and patch governance</option>
<option value="day-042.html">Day 42: GKE cluster architecture and Autopilot vs Standard</option>
<option value="day-043.html">Day 43: GKE workload primitives, Pods, Deployments and Jobs</option>
<option value="day-044.html">Day 44: Service networking and persistent volumes</option>
<option value="day-045.html">Day 45: Probes, secrets and workload failures</option>
<option value="day-046.html">Day 46: Fleet, supply chain and mesh trade-offs</option>
<option value="day-047.html">Day 47: Cloud Run and event-driven functions</option>
<option value="day-048.html">Day 48: Workflows and runtime selection</option>
<option value="day-049.html" selected>Day 49: VPC address and route design</option>
<option value="day-050.html">Day 50: Firewall policy and private API access</option>
<option value="day-051.html">Day 51: Peering, Shared VPC, PSC and NAT</option>
<option value="day-052.html">Day 52: DNS, hybrid transit and network diagnosis</option>
<option value="day-053.html">Day 53: Load-balancer architecture</option>
<option value="day-054.html">Day 54: Health checks, certificates and draining</option>
<option value="day-055.html">Day 55: CDN, WAF and traffic management</option>
<option value="day-056.html">Day 56: Hybrid topology and failure domains</option>
<option value="day-057.html">Day 57: Dedicated Interconnect, Partner and MACsec</option>
<option value="day-058.html">Day 58: Cloud Storage classes, lifecycle and autotiering</option>
<option value="day-059.html">Day 59: Storage security, signed URLs and object retention</option>
<option value="day-060.html">Day 60: Cloud SQL high availability, replicas and scaling</option>
<option value="day-061.html">Day 61: Cloud SQL maintenance, backups and recovery</option>
<option value="day-062.html">Day 62: AlloyDB architecture and columnar accelerator</option>
<option value="day-063.html">Day 63: Spanner architecture, TrueTime and schema design</option>
<option value="day-064.html">Day 64: Bigtable rowkey design and replication topology</option>
<option value="day-065.html">Day 65: Firestore data modeling and security rules</option>
<option value="day-066.html">Day 66: Memorystore Redis/Memcached caching strategies</option>
<option value="day-067.html">Day 67: Gate 3 review: Core infrastructure</option>
</optgroup>
<optgroup label="Integration, analytics and automation">
<option value="day-068.html">Day 68: Pub/Sub architecture, schemas and ordering</option>
<option value="day-069.html">Day 69: Pub/Sub dead-letter topics and push/pull modes</option>
<option value="day-070.html">Day 70: Cloud Tasks and Cloud Scheduler orchestration</option>
<option value="day-071.html">Day 71: Eventarc trigger topologies and audit routing</option>
<option value="day-072.html">Day 72: BigQuery storage, partition and cluster layout</option>
<option value="day-073.html">Day 73: BigQuery SQL, views and materialized view design</option>
<option value="day-074.html">Day 74: BigQuery reservations, BI Engine and slot pricing</option>
<option value="day-075.html">Day 75: Dataproc clusters, autoscaling and serverless</option>
<option value="day-076.html">Day 76: Cloud Dataflow pipeline design and windowing</option>
<option value="day-077.html">Day 77: Dataflow streaming, watermarks and checkpoints</option>
<option value="day-078.html">Day 78: Dataplex governance, lakes and data discovery</option>
<option value="day-079.html">Day 79: Cloud Composer orchestration and DAG lifecycle</option>
<option value="day-080.html">Day 80: Data Fusion and visual pipeline integration</option>
<option value="day-081.html">Day 81: Looker studio, Looker platform and semantic layers</option>
<option value="day-082.html">Day 82: Gate 4 review: Data and analytics</option>
</optgroup>
<optgroup label="DevOps, SRE and multi-cloud">
<option value="day-083.html">Day 83: Cloud Build triggers, pools and pipeline security</option>
<option value="day-084.html">Day 84: Artifact Registry layout, cleanup and remote repos</option>
<option value="day-085.html">Day 85: Cloud Deploy delivery pipelines and canaries</option>
<option value="day-086.html">Day 86: Terraform GCP provider, state and remote backend</option>
<option value="day-087.html">Day 87: Terraform module patterns and refactoring</option>
<option value="day-088.html">Day 88: Cloud Monitoring SLI, SLO and error budget design</option>
<option value="day-089.html">Day 89: Cloud Trace, Profiler and distributed diagnostics</option>
<option value="day-090.html">Day 90: Incident management, alerting and runbook hygiene</option>
<option value="day-091.html">Day 91: Disaster recovery strategies: cold, warm and hot</option>
<option value="day-092.html">Day 92: Cross-region replication and failover validation</option>
<option value="day-093.html">Day 93: Backup and recovery testing regimens</option>
<option value="day-094.html">Day 94: Hybrid identity, ADFS, Okta and directory sync</option>
<option value="day-095.html">Day 95: Anthos/GKE Enterprise multi-cloud architecture</option>
<option value="day-096.html">Day 96: Migration center, assessment and cost models</option>
<option value="day-097.html">Day 97: Database Migration Service and schema conversion</option>
<option value="day-098.html">Day 98: Transfer Appliance, Storage Transfer Service</option>
<option value="day-099.html">Day 99: FinOps foundation, labels and commit discounts</option>
<option value="day-100.html">Day 100: CUD optimization, flexible vs standard</option>
<option value="day-101.html">Day 101: Re-architecting legacy monoliths for cloud</option>
<option value="day-102.html">Day 102: Strangler fig pattern and API facade design</option>
<option value="day-103.html">Day 103: Container migration with Migrate for Anthos</option>
<option value="day-104.html">Day 104: Zero-trust architecture with BeyondCorp</option>
<option value="day-105.html">Day 105: Regulatory compliance: HIPAA, PCI and GDPR</option>
<option value="day-106.html">Day 106: Data residency, sovereign controls and Assured Workloads</option>
<option value="day-107.html">Day 107: Cloud Armor advanced WAF rules and ML defense</option>
<option value="day-108.html">Day 108: Network security: Cloud IDS, IPS and inspection</option>
<option value="day-109.html">Day 109: Secret lifecycle and hardware security modules</option>
<option value="day-110.html">Day 110: Threat detection, Event Threat Detection</option>
<option value="day-111.html">Day 111: Chaos engineering and resilience testing</option>
<option value="day-112.html">Day 112: Canary, blue-green and A/B release mechanics</option>
<option value="day-113.html">Day 113: Observability at scale: multi-project metrics</option>
<option value="day-114.html">Day 114: Secure software supply chain with SLSA</option>
<option value="day-115.html">Day 115: Binary Authorization in enterprise delivery</option>
<option value="day-116.html">Day 116: Infrastructure as code governance and Sentinel</option>
<option value="day-117.html">Day 117: Operational runbooks, game days and blameless postmortems</option>
<option value="day-118.html">Day 118: Gate 5 review: Delivery, SRE and operations</option>
</optgroup>
<optgroup label="Architecture defense and case studies">
<option value="day-119.html">Day 119: Enterprise multi-tenant SaaS architecture</option>
<option value="day-120.html">Day 120: Global real-time gaming platform design</option>
<option value="day-121.html">Day 121: Healthcare data platform with FHIR/HIPAA</option>
<option value="day-122.html">Day 122: Global financial clearing and settlement</option>
<option value="day-123.html">Day 123: IoT telemetry ingest and stream analytics</option>
<option value="day-124.html">Day 124: Media streaming and transcoding at scale</option>
<option value="day-125.html">Day 125: Retail e-commerce flash sale architecture</option>
<option value="day-126.html">Day 126: Modernizing mainframe workloads on GCP</option>
<option value="day-127.html">Day 127: Autonomous vehicle sensor data platform</option>
<option value="day-128.html">Day 128: Disaster recovery design across three clouds</option>
<option value="day-129.html">Day 129: Multi-region active-active database patterns</option>
<option value="day-130.html">Day 130: Zero-trust enterprise workforce architecture</option>
<option value="day-131.html">Day 131: Lifecycle, exceptions and adoption</option>
<option value="day-132.html">Day 132: Customer success and platform outcomes</option>
<option value="day-133.html">Day 133: Operations integration and remediation</option>
</optgroup>
<optgroup label="Data, AI and distributed correctness">
<option value="day-134.html">Day 134: Warehouse foundations and query costs</option>
<option value="day-135.html">Day 135: Warehouse security and reporting</option>
<option value="day-136.html">Day 136: Batch and streaming processing choices</option>
<option value="day-137.html">Day 137: Streaming correctness and CDC</option>
<option value="day-138.html">Day 138: Lakehouse and open table design</option>
<option value="day-139.html">Day 139: Catalogs, lineage and data contracts</option>
<option value="day-140.html">Day 140: ML lifecycle and model selection</option>
<option value="day-141.html">Day 141: Build a small grounded-answer flow</option>
<option value="day-142.html">Day 142: Bounded tools and enterprise assistants</option>
<option value="day-143.html">Day 143: AI security and evaluation</option>
<option value="day-144.html">Day 144: AI serving and infrastructure choices</option>
<option value="day-145.html">Day 145: Distributed state and regional correctness</option>
</optgroup>
<optgroup label="Discovery, cases and exam preparation">
<option value="day-146.html">Day 146: Case analysis and discovery method</option>
<option value="day-147.html">Day 147: Extract facts and numeric requirements</option>
<option value="day-148.html">Day 148: Map requirements and conflicts</option>
<option value="day-149.html">Day 149: Discovery: business, load and recovery</option>
<option value="day-150.html">Day 150: Discovery: data, regulation and skills</option>
<option value="day-151.html">Day 151: Discovery: budget, risks and success</option>
<option value="day-152.html">Day 152: EHR Healthcare — facts and migration constraints</option>
<option value="day-153.html">Day 153: EHR Healthcare — defend the design</option>
<option value="day-154.html">Day 154: Altostrat Media — content and AI requirements</option>
<option value="day-155.html">Day 155: Altostrat Media — architecture defense</option>
<option value="day-156.html">Day 156: Cymbal Retail — catalog and commerce requirements</option>
<option value="day-157.html">Day 157: Cymbal Retail — architecture defense</option>
<option value="day-158.html">Day 158: KnightMotives — modernization requirements</option>
<option value="day-159.html">Day 159: KnightMotives — architecture defense</option>
<option value="day-160.html">Day 160: Case synthesis and feedback</option>
<option value="day-161.html">Day 161: Changed-constraint design exercise</option>
<option value="day-162.html">Day 162: Exam domain mapping and sample questions</option>
<option value="day-163.html">Day 163: Timed reasoning and source-backed limits</option>
<option value="day-164.html">Day 164: Readiness plan and remaining repairs</option>
</optgroup>
<optgroup label="Multi-team architecture and synthesis">
<option value="day-165.html">Day 165: Landing zones and multi-team platform boundaries</option>
<option value="day-166.html">Day 166: Production identity across teams</option>
<option value="day-167.html">Day 167: API contracts and compatibility</option>
<option value="day-168.html">Day 168: Sustainability and assisted operations</option>
<option value="day-169.html">Day 169: Capacity allocation and overload governance</option>
<option value="day-170.html">Day 170: Compute and database decision synthesis</option>
<option value="day-171.html">Day 171: Network decision synthesis</option>
<option value="day-172.html">Day 172: Storage, messaging and limits synthesis</option>
<option value="day-173.html">Day 173: Consulting, portfolio and customer handover</option>
</optgroup>
<optgroup label="Final gate and capstone defenses">
<option value="day-174.html">Day 174: Gate 6 — Integrated readiness and remediation</option>
<option value="day-175.html">Day 175: Capstone 1 — Landing-zone defense</option>
<option value="day-176.html">Day 176: Capstone 2 — Regulated-workload defense</option>
<option value="day-177.html">Day 177: Capstone 3 — Global-application defense</option>
<option value="day-178.html">Day 178: Capstone 4 — Migration defense</option>
<option value="day-179.html">Day 179: Capstone 5 — Cost and reliability rescue</option>
</optgroup>
<optgroup label="Final review and rest">
<option value="day-180.html">Day 180: Final review, logistics and rest</option>
</optgroup>"""

print(f"Jump options lines: {len(DAY_JUMP.splitlines())}")
