#!/usr/bin/env python3
"""Topic 2 technical text for Day 7."""

TOPIC_02_TECH = '''<p><strong class="side-heading">Subtopics in this discussion:</strong></p>
<ol>
<li>Package formats (deb vs rpm) and archive structure</li>
<li>Repository metadata, mirrors, and GPG cryptographic signature verification</li>
<li>Dependency graph resolution, conflict handling, and transaction locks</li>
<li>Automated system updates, unattended-upgrades, and repository pinning</li>
<li>Immutable infrastructure: pre-baked VM images (Packer) vs runtime package installation</li>
</ol>

<h4>Package formats (deb vs rpm) and archive structure</h4>
<p><strong class="side-heading">What it is in general:</strong> Linux software distribution relies on standardized archive formats: Debian/Ubuntu distributions utilize the <strong class="keyword">deb</strong> format (an <code>ar</code> archive containing control metadata, binary tarballs, and installation scripts), while Enterprise Linux distributions (Red Hat, CentOS, Rocky Linux, Fedora) utilize the <strong class="keyword">rpm</strong> (RPM Package Manager) format (a cpio archive with binary header metadata and payload data). Packages encapsulate compiled application binaries, library dependencies, default configuration files, and lifecycle maintainer scripts (pre/post-installation and pre/post-removal hooks) executed with root privileges during package state transitions.</p>
<p><strong class="side-heading">Relevance to a cloud architect:</strong> Cloud architects standardizing operating system baselines must account for packaging differences across distributions. Package maintainer scripts execute arbitrary code as root: installing unvetted third-party packages introduces severe supply chain risks, trojanized pre-install hooks, and configuration drift across cloud environments.</p>
<p><strong class="side-heading">Relevance to GCP:</strong> Compute Engine provides optimized public images for both Debian/Ubuntu (APT) and RHEL/Rocky (DNF). Google Cloud packages (such as the Google Cloud CLI, Cloud Ops Agent, and OS Login PAM modules) are distributed via dedicated Google Cloud APT and YUM package repositories. Primary documentation: <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) package manager description (accessed 2026-10-04)</a>.</p>
<p><strong class="side-heading">Further study:</strong> <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) query and verification modes (accessed 2026-10-04)</a>; <a href="https://man7.org/linux/man-pages/man1/dpkg.1.html#DESCRIPTION">dpkg(1) Debian package manager description (accessed 2026-10-04)</a>.</p>

<h4>Repository metadata, mirrors, and GPG cryptographic signature verification</h4>
<p><strong class="side-heading">What it is in general:</strong> Package managers retrieve packages from HTTP/HTTPS repository mirrors. To guarantee integrity and authenticity against man-in-the-middle (MITM) attacks and mirror compromises, repositories publish cryptographic metadata files (e.g. <code>InRelease</code> in Debian, <code>repomd.xml</code> in RHEL) signed with a detached <strong class="keyword">GPG Key</strong> (GNU Privacy Guard). The metadata lists SHA-256 cryptographic checksums for every package in the repository. When a client runs <kbd>apt-get update</kbd> or <kbd>dnf check-update</kbd>, the package manager downloads the metadata, verifies the GPG digital signature against local trusted keyrings (in <code>/etc/apt/keyrings/</code> or <code>/etc/pki/rpm-gpg/</code>), and verifies that package checksums match prior to execution.</p>
<p><strong class="side-heading">Relevance to a cloud architect:</strong> Expired, revoked, or rotated GPG repository keys cause automated image builds and instance auto-scaling events to fail catastrophically. Architects enforce repository pinning and private internal package mirrors (e.g. Artifact Registry) to eliminate runtime dependency on public internet package repositories.</p>
<p><strong class="side-heading">Relevance to GCP:</strong> Google Cloud Artifact Registry supports private Debian (APT) and RPM (YUM) package repositories, allowing enterprise architects to host proprietary internal packages, mirror approved upstream packages, and enforce VPC Service Controls to prevent data exfiltration. Primary documentation: <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) cryptographic verification and signature checks (accessed 2026-10-04)</a>.</p>
<p><strong class="side-heading">Further study:</strong> <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) --import and signature verification (accessed 2026-10-04)</a>; <a href="https://manpages.debian.org/bookworm/apt/apt-secure.8.en.html#DESCRIPTION">apt-secure(8) archive authentication in Debian (accessed 2026-10-04)</a>.</p>

<h4>Dependency graph resolution, conflict handling, and transaction locks</h4>
<p><strong class="side-heading">What it is in general:</strong> Linux applications depend on shared libraries (e.g. glibc, openssl) and runtime dependencies. Modern package managers utilize Boolean Satisfiability (SAT) solvers (e.g. libsolv in DNF, internal solvers in APT) to resolve transitive dependency graphs, calculate upgrade paths, and prevent package conflicts. To maintain state consistency, package managers enforce exclusive filesystem advisory locks (e.g. <code>/var/lib/dpkg/lock-frontend</code>, <code>/var/lib/rpm/.rpm.lock</code>). If an automated background process or previous failed installation holds the lock, subsequent package commands abort immediately.</p>
<p><strong class="side-heading">Relevance to a cloud architect:</strong> Concurrency contention over package manager lock files is a primary failure mode in VM initialization scripts: if an instance startup script attempts to install packages while an automated system update process is running in the background, the startup script crashes and marks the VM unhealthy in load balancer pools.</p>
<p><strong class="side-heading">Relevance to GCP:</strong> Compute Engine instance startup scripts must implement retry loops with exponential backoff when executing package installation commands, explicitly waiting for unattended-upgrades or cloud-init background processes to release package manager lock files. Primary documentation: <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) transaction lock and database management (accessed 2026-10-04)</a>.</p>
<p><strong class="side-heading">Further study:</strong> <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) transaction sets and rollback semantics (accessed 2026-10-04)</a>; <a href="https://manpages.debian.org/bookworm/apt/apt-get.8.en.html#DESCRIPTION">apt-get(8) dependency resolution algorithms (accessed 2026-10-04)</a>.</p>

<h4>Automated system updates, unattended-upgrades, and repository pinning</h4>
<p><strong class="side-heading">What it is in general:</strong> Maintaining operating system hygiene requires regular application of Common Vulnerabilities and Exposures (CVE) security patches. Linux daemons like <strong class="keyword">unattended-upgrades</strong> (Debian/Ubuntu) and <strong class="keyword">dnf-automatic</strong> (RHEL/Rocky) poll upstream repositories daily to download and install security errata automatically. To prevent automated upgrades from inadvertently breaking critical application dependencies, package managers support <strong class="keyword">Repository Pinning</strong> (APT preferences) and version locking (<kbd>dnf versionlock</kbd>), constraining specific packages to designated release channels or immutable version numbers.</p>
<p><strong class="side-heading">Relevance to a cloud architect:</strong> Enabling uncoordinated automated updates on production multi-instance clusters introduces severe availability risks: an unexpected kernel or library update can reboot instances simultaneously or introduce breaking API changes. Architects coordinate rolling OS patch management using central orchestration rather than unmanaged VM-local cron jobs.</p>
<p><strong class="side-heading">Relevance to GCP:</strong> Google Cloud VM Manager (part of Compute Engine) provides centralized OS Patch Management, allowing architects to define patch deployment schedules, enforce pre-patch and post-patch validation scripts, configure reboot policies, and generate fleet-wide compliance dashboards. Primary documentation: <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) package verification and version comparison (accessed 2026-10-04)</a>.</p>
<p><strong class="side-heading">Further study:</strong> <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) --verify and file modification tracking (accessed 2026-10-04)</a>; <a href="https://manpages.debian.org/bookworm/apt/apt_preferences.5.en.html#DESCRIPTION">apt_preferences(5) pinning specification (accessed 2026-10-04)</a>.</p>

<h4>Immutable infrastructure: pre-baked VM images (Packer) vs runtime package installation</h4>
<p><strong class="side-heading">What it is in general:</strong> Software deployment models on Linux virtual machines follow two competing paradigms: <strong class="keyword">Runtime Provisioning</strong> (booting a generic base OS image and running <kbd>apt-get install</kbd> in a startup script) versus <strong class="keyword">Immutable Golden Images</strong> (pre-installing and compiling all application binaries and package dependencies during CI/CD build pipelines using tools like HashiCorp Packer, producing a frozen, read-only VM disk image).</p>
<p><strong class="side-heading">Relevance to a cloud architect:</strong> Runtime provisioning is fragile: instance boot times are extended by several minutes, auto-scaling events stall, and any upstream repository downtime, DNS glitch, or package mirror rate-limit causes new VM instances to fail to boot. Pre-baked immutable images guarantee deterministic, instantaneous startup (under 30 seconds) and eliminate external internet dependencies at launch time.</p>
<p><strong class="side-heading">Relevance to GCP:</strong> In Compute Engine Managed Instance Groups (MIGs), architects mandate custom golden images referenced in Instance Templates. Golden images are created via automated Packer pipelines, tested in isolation, and stored in Google Cloud Custom Images families, enabling seamless rolling updates with zero runtime package installations. Primary documentation: <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) package installation and query operations (accessed 2026-10-04)</a>.</p>
<p><strong class="side-heading">Further study:</strong> <a href="https://man7.org/linux/man-pages/man8/rpm.8.html#DESCRIPTION">rpm(8) database rebuild and integrity checks (accessed 2026-10-04)</a>; <a href="https://man7.org/linux/man-pages/man1/dpkg-query.1.html#DESCRIPTION">dpkg-query(1) package status inspection (accessed 2026-10-04)</a>.</p>

<table><caption>Package management lifecycle stages</caption>
<thead><tr><th>Stage</th><th>Mechanism</th><th>Primary Risk</th><th>Defensive Control</th></tr></thead>
<tbody>
<tr><td>Metadata Fetch</td><td>HTTP GET InRelease / repomd.xml</td><td>Mirror outage or network timeout</td><td>Internal Artifact Registry mirror.</td></tr>
<tr><td>Integrity Verification</td><td>GPG detached signature validation</td><td>Expired or untrusted signing key</td><td>Explicit keyring pinning in sources.list.</td></tr>
<tr><td>Dependency Solve</td><td>Transitive SAT graph resolution</td><td>Version conflicts or broken deps</td><td>Version locking and repository priority pinning.</td></tr>
<tr><td>Filesystem Commit</td><td>Unpack binaries and run maintainer hooks</td><td>Arbitrary code execution as root</td><td>Pre-baked immutable images built in CI/CD.</td></tr>
</tbody></table>

{FIG_7_2_HTML}

<p><strong class="side-heading">Concrete example:</strong> A web service startup script executes <kbd>apt-get update &amp;&amp; apt-get install -y nginx</kbd> when new VMs boot in an autoscaling group. An upstream mirror maintainer rotates the repository signing GPG key without prior announcement. When a traffic surge triggers auto-scaling, newly provisioned VM instances execute the startup script, encounter a GPG verification signature failure (<code>EXPKEYSIG</code>), abort with exit code 100, and fail their load balancer health checks. Replacing the runtime install script with a pre-baked Compute Engine custom image containing pre-installed nginx resolves the issue, reducing VM boot time from 210 seconds to 18 seconds.</p>
<p><strong class="side-heading">Evidence limit:</strong> Successful package installation proves only that files were unpacked to disk and maintainer post-install scripts exited with code 0; it does not prove that the installed service daemon is running, that its configuration file is free of runtime errors, or that network firewall rules permit traffic to its listening port.</p>'''

print("Topic 2 tech defined.")
