"""Day 130 source data: service ownership, change, incident, runbook, and catalog."""

DAY_NUM = 130

def eight_steps(topic, seed, action, expected, failure, closeout):
    """Eight fully specified local/tabletop execution steps; no cloud changes."""
    return [
        f"**Stage 1: Preflight the synthetic case.** Create a local file named `day-130-{topic}.md`. Record `mode=tabletop`, `project=none`, `credentials=none`, and the fixed case input: {seed} Record the service boundary as `Brightloaf checkout API → orders database → payment provider`; mark all facts synthetic. Expected preflight row: `cloud mutations=0; live evidence=0`.",
        f"**Stage 2: Prepare the service inventory.** In the file, add a table with columns `service | customer outcome | dependency | service owner | platform owner | response owner`. Enter one row for `checkout-api | submit one valid order | orders-db + payment | team-checkout | team-platform | primary-on-call`; add the dependency and owner row for `orders-db | persist one order | managed database | team-checkout | team-platform | database-on-call`. Expected: every row has exactly one accountable service owner and one escalation contact.",
        f"**Stage 3: Author the decision record.** Add sections `scope`, `inputs`, `decision`, `evidence`, `rollback`, and `open risks`. Use this exact input set: `service={topic}; change={action}; target={seed}; success={expected}; abort={failure}`. Write the decision in one sentence and name the person/role authorized to approve it. Expected: no field is blank and the decision can be checked against an observable signal.",
        f"**Stage 4: Run the planned tabletop.** Use the supplied event `10:02 alert opens; 10:04 on-call acknowledges; 10:07 service owner joins; 10:12 mitigation proposed`. Assign incident commander=`platform-on-call`, operations lead=`team-checkout`, communications lead=`support-on-call`; record who has authority to pause the change. Apply this topic's action: {action} Expected: a timestamped sequence with one named decision owner at every handoff.",
        f"**Stage 5: Verify the expected state.** Evaluate this exact checkpoint: `{expected}`. Record `pass/fail`, the observable evidence needed (ticket/change record, deployment revision, runbook result, or catalog schema as applicable), and the owner who supplies it. Expected result: the evidence proves both the service outcome and the handoff; an approval alone is not success.",
        f"**Stage 6: Rehearse the bounded failure.** Change only this input: `{failure}`. Keep all other values fixed. Mark the first expected signal, the role that declares stop/rollback, and the customer communication trigger. Expected: a bounded decision with explicit abort condition; do not execute fault injection or contact a live service.",
        f"**Stage 7: Diagnose and record remediation.** Using only the fixed timeline and case input, write `symptom → evidence to collect → likely boundary → alternative explanation → next safe action`. The diagnostic must distinguish supplied facts from inference. Expected: the named owner can reproduce the decision from the record, and the remediation has a verification signal and follow-up owner.",
        f"**Stage 8: Close out the exercise.** Add `decision status`, `rollback/containment`, `follow-up owner + due date`, `catalog/runbook/change link`, and `limitations`. For this local tabletop, set `cloud cleanup=not applicable; spend=none; live outcome=not observed`. Expected: the artifact is self-contained and ready to attach to Day 130 exit evidence. {closeout}"
    ]

topics = [
    {
        "key": "topic-01", "title": "Operating model and service ownership",
        "overview": "The operating model assigns decision rights across platform and product teams. Platform engineering owns shared foundations, paved-road interfaces, guardrails, and platform reliability; the product team owns its service behavior, customer SLOs, application data, and first-line diagnosis. Shared ownership must resolve at an explicit interface: a component can have a provider and a consumer, but an incident still needs one accountable service owner. This belongs after the proven baseline because Day 130 packages it as a supported service with an intake, owner, boundary, and escalation path. A request can cross a team boundary without a named decision owner. The resulting delay extends customer impact and obscures follow-up accountability.",
        "preview": "A checkout alert reaches the platform team although only the product team can safely disable the faulty feature. Customers continue to receive failed orders while responders negotiate ownership.",
        "technical": "A useful responsibility model names one accountable owner per service outcome and separates it from contributing roles. The platform team owns shared network, identity, deployment primitives, policy, and support interfaces; the product team owns application configuration, data semantics, SLOs, and customer impact. A RACI matrix is a communication contract, not an authorization system: IAM, deployment gates, and on-call access still enforce actual permissions. Keep service boundaries visible in an inventory: service, dependency, tier, owner, pager, support hours, runbook, change path, and escalation. The trade-off is central consistency versus local autonomy. Central review can reduce unsafe variation but add queue time; self-service can improve flow but must constrain supported inputs and reveal who operates the result. Measure handoff time, ownership completeness, and repeat escalations, not just team names.\n\nBoundary test: for every dependency, record provider owner, consumer owner, and the signal each can observe. If either side cannot inspect the signal or execute the mitigation, document an escalation path. A shared Slack channel does not itself establish accountability.",
        "reference": "https://docs.cloud.google.com/architecture/framework/operational-excellence/operational-readiness-and-performance-using-cloudops", "reference_label": "Google Cloud Well-Architected Framework: CloudOps operational readiness and team responsibilities (accessed 2026-09-29)",
        "questions": ["Which role owns the customer outcome during a cross-team incident?", "Which operational signals can the service owner inspect without platform intervention?", "What is the escalation path outside normal support hours?"],
        "scenario": {"scenario": "Synthetic Brightloaf case: a checkout configuration rollout raises payment timeouts. The product owner assumes platform operations owns rollback; platform operations can see deployment health but cannot approve a business feature change.", "impact": "The alert is acknowledged but no one pauses the rollout. Orders fail for nine minutes in the tabletop timeline; this is a scenario, not an observed incident.", "constraints": "Preserve order integrity, payment reconciliation, and separation of duties. The incident commander coordinates; only the authorized service owner approves application rollback.", "facts": "Supplied facts are synthetic: 10:02 alert, 10:04 acknowledgment, 10:07 service owner joins, 10:12 mitigation proposed. No production telemetry was examined.", "inference": "The ownership gap could explain the delay if logs show an approval handoff blocked action. Competing explanations include an incomplete alert, a technically unsafe rollback, or payment-provider degradation.", "root": "Potential causal chain: responsibility matrix omits rollback authority → responders interpret platform ownership as application decision authority → product owner is paged late → mitigation decision is delayed. Confirm with the incident timeline and access-control records.", "diagnostic_steps": ["Compare alert, acknowledgment, page, decision, and mitigation timestamps; mark observed versus supplied.", "Inspect the service inventory for accountable owner, backup, pager, and rollback authority.", "Check who had permission and technical ability to pause the rollout; separate authorization from capability.", "Test alternative causes: provider status, deployment health, and application error signal.", "Name the first handoff without an owner and quantify its duration from recorded timestamps."], "fix": "Assign the checkout service owner responsibility for customer outcome and application rollback, platform team responsibility for deployment controls and shared infrastructure, and an incident commander responsibility for coordination. Add backup contacts and a tested escalation path.", "verify": "Tabletop a second alert and confirm the service owner is paged, the commander is named, the permitted rollback action is clear, and a recovery signal is stated before the exercise closes.", "residual": "A matrix can become stale and does not grant permissions. Review it after team, service, or support changes; test access and paging separately.", "diagram": ("Checkout alert fires", "Rollback authority is unassigned", "Teams wait at ownership boundary", "Name service owner and incident commander", "Owner approves; recovery signal is checked")},
        "lab": {"name": "Responsibility matrix and service boundary", "goal": "Produce a reviewable owner map for a synthetic checkout service.", "expected": "A responsibility matrix and escalation decision record with no unowned customer outcome.", "mode": "local tabletop; no cloud, credentials, or live incident", "prereq": "Day 129 baseline and Day 81 operating artifact, or mark missing inputs explicitly", "preflight": "Use a local editor. Treat all Brightloaf values as synthetic; create no project or resource.", "steps": eight_steps("ownership", "checkout-api; product team owns customer behavior; platform team owns shared deployment and identity", "assign customer outcome to team-checkout and shared platform controls to team-platform", "one accountable service owner, a named commander, and a tested escalation contact", "service owner unavailable at 10:07; backup contact must be paged", "Keep the matrix and note a quarterly or team-change review trigger."), "file": "day-130-topic-01-ownership.md", "verification": "Acceptance check: `checkout-api` has exactly one accountable service owner, platform dependencies have provider owners, and each escalation has a role plus a contact path.", "accept": "Save the completed owner matrix, boundary, and escalation record in `day-130-topic-01-ownership.md`.", "trouble": "If both teams claim or disclaim the same decision, split outcome ownership from platform capability and identify one approver for the specific change.", "cleanup": "No resources are created. Keep the synthetic artifact; no cloud cleanup or charges apply."}
    },
    {
        "key": "topic-02", "title": "Change management and release governance",
        "overview": "Change management makes risk, authorization, rollout, evidence, and recovery explicit before a change reaches users. Release governance should scale review to risk: a routine, reversible, automated change can use a lightweight standard path, while a high-impact or hard-to-reverse change needs explicit review and a tested backout. Progressive delivery limits blast radius and creates a decision point from observed signals. A change ticket is useful only when linked to an artifact, scope, approver, verification, and rollback owner. This topic turns the Day 129 delivery baseline into a service promise that has supported change paths. A release expands to every user before the health signal is checked. The larger blast radius increases recovery time and the number of affected customers.",
        "preview": "A schema change is released to every checkout instance before compatibility is verified. The resulting rollback cannot restore the old application because the data change is irreversible.",
        "technical": "A governed change path connects request → impact and risk assessment → approval where required → immutable build artifact → staged rollout → health evaluation → continue, pause, or rollback → closure and learning. The release owner controls the deployment; the service owner accepts customer risk; the change approver is required only where policy defines it; an emergency path should record retrospective review. Progressive exposure reduces the population at risk but does not make a bad release safe if telemetry is delayed, cohorts are biased, or rollback is untested. A rollback plan must account for database compatibility, external side effects, and configuration state, not only the binary. Prefer backward-compatible expand/migrate/contract schema evolution. Evidence includes change ID, artifact digest, target, approval, rollout timestamps, SLO/error signals, decision, and final revision. The trade-off is review latency versus control: automate low-risk checks and reserve human approval for decisions with meaningful uncertainty or impact.\n\nExit criteria must be measurable and time-bounded: compare error rate and latency to a stated baseline over a representative window, then stop when a threshold is crossed. Never infer successful release from a green pipeline alone.",
        "reference": "https://sre.google/workbook/canarying-releases/", "reference_label": "Google SRE Workbook: Canarying Releases (accessed 2026-09-29)",
        "questions": ["What is the exposure unit and how is it increased?", "Who can pause or reverse the release?", "Does rollback include schema, messages, and external side effects?"],
        "scenario": {"scenario": "Synthetic scenario: Brightloaf prepares release r42 with a database field rename and a checkout service update. The team proposes a one-step full rollout and has no recorded compatibility check.", "impact": "A failure could break old and new application versions during rollout and prevent a simple binary rollback. No real release or outage is asserted.", "constraints": "Maintain one fulfillment per order, preserve payment reconciliation, avoid exposing secrets in build logs, and use only an approved change path.", "facts": "Synthetic inputs: current revision r41; proposed r42; 10% canary cohort; abort if checkout error ratio is above 1% for two consecutive five-minute windows; migration compatibility is unverified.", "inference": "The risky element is the unverified compatibility plus a full rollout, not the version label. Confirm by inspecting migration plan, cohort health, and rollback rehearsal.", "root": "Potential cause: release plan omits compatibility and explicit abort checks → application versions overlap against a renamed field → requests fail and binary rollback may still encounter changed schema.", "diagnostic_steps": ["Read the change record and identify artifact digest, service, data migration, approver, and rollback owner.", "Map old and new application versions to schema reads/writes; mark any incompatible overlap.", "Check baseline and canary error/latency windows; do not use a single aggregate green status.", "Confirm the abort threshold and who is authorized to pause at 10% exposure.", "Separate a rollback of application code from a forward-compatible data recovery action."], "fix": "Use an expand-and-contract migration: add compatible field, deploy code that supports old and new fields, backfill and verify, then remove old field only after all readers/writers move. Release to a small cohort with stated SLO gates and rehearse rollback before expansion.", "verify": "The record contains a compatible transition proof, cohort size, two-window abort test, named pause authority, artifact digest, and a rollback or forward-recovery step. Preserve the single-fulfillment invariant.", "residual": "A canary may not include rare user paths, and a delayed metric can make a gate late. Schema cleanup and external side effects may not be reversible; retain forward recovery and communication steps.", "diagram": ("r42 requested for release", "Full rollout skips compatibility gate", "Old and new code conflict on schema", "Canary with two-window SLO gate", "Pause or expand after evidence")},
        "lab": {"name": "Risk-based release and rollback record", "goal": "Build a staged change plan with an explicit pause rule and data-safe recovery.", "expected": "A change record for r42 that prevents incompatible rollout and has measurable gates.", "mode": "local tabletop; no deployment", "prereq": "Day 129 pipeline evidence or a clearly marked synthetic substitute", "preflight": "Create a local note only. Do not deploy, change a project, or use credentials.", "steps": eight_steps("change", "current=r41; proposed=r42; cohort=10%; abort=error ratio >1% for two consecutive 5-minute windows; schema compatibility=unverified", "replace full rollout with compatibility review, 10% canary, measured gate, and named rollback/forward-recovery owner", "compatibility is proven before expansion; gate uses two consecutive windows; one authorized pause owner is named", "schema compatibility remains unverified at approval time; choose hold, not rollout", "Close with change record, staged scope, rollback notes, and explicit no-deploy status."), "file": "day-130-topic-02-change.md", "verification": "Acceptance check: hold when compatibility is unverified; only expand after both windows pass and migration safety is evidenced.", "accept": "Save the staged release decision, threshold, evidence fields, and recovery plan in `day-130-topic-02-change.md`.", "trouble": "If no reliable baseline or rollback exists, classify the change as not ready and record the missing evidence and owner.", "cleanup": "No deployment occurred. Preserve the change record; there are no resources to remove."}
    },
    {
        "key": "topic-03", "title": "Incident, problem, and change processes",
        "overview": "Incident management restores service through coordinated response; problem management investigates recurring or systemic causes; change management controls the corrective modification. These are related records with distinct goals and clocks. During an incident, assign a commander, operations lead, and communications lead as needed, state known facts, and maintain a current decision log. After stabilization, connect the incident to a problem record and tracked corrective actions. ITIL terms are useful awareness vocabulary, but the specific practice and roles should match the organization’s adopted process. A severity label by itself does not coordinate work. Responders duplicate investigation and customer updates, prolonging service disruption and reducing trust.",
        "preview": "Two teams open separate incident threads for the same checkout failure and send conflicting recovery updates. Customers cannot tell whether orders are safe to retry.",
        "technical": "The incident record is the live coordination surface: impact, start time, severity rationale, commander, operations and communications roles, timeline, customer updates, decisions, and current status. The incident commander manages coordination and priorities; technical leads investigate and execute approved actions. Closure follows service recovery, while a problem record carries causal analysis and prevention work beyond the response window. A change record governs fixes that alter production. Join the records by stable identifiers so a postmortem action can be traced to an approved change and verification. Avoid equating a status page update with recovery evidence or a closed incident with solved systemic risk. Signals should include customer-facing SLOs and business invariants, such as no duplicate fulfillment after retry. Trade-offs include response structure overhead and the cost of under-coordination; use clear roles at a threshold appropriate to impact and complexity. Keep timelines factual and distinguish observation, inference, and unknowns.\n\nA blameless review asks how system conditions and process design shaped the event, then assigns owners and due dates to improvements. Follow-up without an owner, measurable completion test, and review date is not a control.",
        "reference": "https://docs.cloud.google.com/architecture/framework/operational-excellence/manage-incidents-and-problems", "reference_label": "Google Cloud Well-Architected Framework: Manage incidents and problems (accessed 2026-09-29)",
        "questions": ["What customer impact and business invariant define recovery?", "Which record coordinates the live response and which tracks prevention?", "Can every action be tied to an owner, due date, and verification?"],
        "scenario": {"scenario": "Synthetic tabletop: after a checkout timeout alert, responders open two incident threads. Support says retry; the application team has not checked whether timed-out payment requests were committed.", "impact": "A retry could duplicate an order if idempotency state is uncertain, while conflicting updates can increase customer contacts. No production event is claimed.", "constraints": "One business fulfillment per order; customer communication must state what is known and what users should do; preserve forensic timeline without assigning blame.", "facts": "Synthetic timeline: 10:02 alert; 10:04 acknowledgment; 10:07 service owner joins; two parallel threads exist; payment commit status is unknown.", "inference": "The coordination split could explain inconsistent messages. Duplicate fulfillment remains a risk to test, not an observed outcome.", "root": "Possible causal chain: no canonical incident record or commander → parallel fact collection and unreviewed retry advice → business invariant is unchecked → customer guidance diverges.", "diagnostic_steps": ["Choose a canonical incident ID and merge timestamps from both threads without erasing original evidence.", "Write the known/unknown list; payment commit status stays unknown until reconciled.", "Assign incident commander, operations lead, and communications lead; name technical investigation owners.", "Check order idempotency key and payment reconciliation evidence before recommending retry.", "After recovery, create linked problem and change actions with owners, due dates, and tests."], "fix": "Declare one coordinated incident record, assign roles, pause unsafe retry guidance until payment state is reconciled, issue an approved customer update, then link the postmortem problem and corrective change records.", "verify": "Close only after customer-facing health is stable and payment/order reconciliation proves at most one fulfillment per order. Track each prevention action to a verified change.", "residual": "Incident command cannot supply missing telemetry or payment truth. Reconciliation can lag; record the uncertainty, customer impact, and next update time.", "diagram": ("Checkout timeout reported twice", "No canonical record or commander", "Conflicting retry advice risks duplicates", "Single incident record and role handoff", "Reconcile payment; verify one fulfillment")},
        "lab": {"name": "Incident timeline and linked follow-up records", "goal": "Create one evidence-based tabletop timeline and link incident, problem, and change work.", "expected": "A canonical response record that protects the one-fulfillment invariant and assigns prevention actions.", "mode": "local tabletop; no incident system or customer contact", "prereq": "Day 129 incident or release artifact, if available", "preflight": "Use only the synthetic timeline below. Do not contact a live team or modify production.", "steps": eight_steps("incident", "10:02 alert; 10:04 acknowledgment; 10:07 owner joins; two threads; payment commit unknown", "merge to one canonical incident record; assign commander/operations/communications; hold retry advice pending reconciliation", "known/unknown list exists; order/payment reconciliation proves no more than one fulfillment before recovery is declared", "support asks customers to retry before payment commit is known; mark advice blocked and name communications approver", "Link the incident to a problem record and corrective change with owner, due date, and verification test."), "file": "day-130-topic-03-incident.md", "verification": "Acceptance check: a single incident identifier, timestamped decision log, named roles, verified retry guidance, and linked follow-up owner/test.", "accept": "Save incident, problem, and change record summaries in `day-130-topic-03-incident.md`.", "trouble": "If commit status is unknown, preserve that as unknown and define the reconciliation evidence required before advising retry.", "cleanup": "This tabletop creates no tickets, notifications, or cloud resources; retain only the local synthetic record."}
    },
    {
        "key": "topic-04", "title": "Runbook automation",
        "overview": "A runbook is an executable or operationally precise procedure for a bounded task. Automation can reduce response time and variation, but it also turns operator assumptions into machine actions. Each automated step needs a trigger, identity, preconditions, scope limit, observable result, timeout, retry behavior, failure path, and audit record. Read-only diagnostics are safer candidates for automation than irreversible writes; write actions need authorization and an explicit stop condition. Keep a human approval for actions whose impact is uncertain or broad. This belongs in the service offering because users need an operational response path with known limits. A remediation script retries every failed request without checking whether its prior write succeeded. The retry can repeat a business action and turn a transient timeout into duplicate work.",
        "preview": "An automated payment-retry runbook treats a timeout as proof that no order was created. Customers can receive duplicate charges or fulfillment.",
        "technical": "Model an automation as observe → validate preconditions → authorize → act within a bounded target set → verify invariant → record result or stop. The trigger must be specific and deduplicated; the execution identity should have the minimum permissions for the action; inputs need schema validation and allowlists; retries must be idempotent or gated by state checks. Set a maximum target count and duration, and fail closed when inventory or identity is ambiguous. Separate diagnostic steps from mutating remediation. An operation should emit a correlation ID, input summary without secrets, before/after state, decision, and result. A timeout means outcome unknown, not action failed. Trade-off: automatic recovery can reduce mean time to restore, while an incorrect or overprivileged automation can amplify a fault. Add a dry-run mode and a human checkpoint for high-impact actions.\n\nFor order or payment workflows, check an idempotency key or authoritative commit state before replay. The success condition is the business invariant, not merely process exit code zero.",
        "reference": "https://docs.cloud.google.com/architecture/framework/operational-excellence/automate-and-manage-change", "reference_label": "Google Cloud Well-Architected Framework: Automate and manage change (accessed 2026-09-29)",
        "questions": ["What exact precondition authorizes the write?", "How does the runbook behave when action outcome is unknown?", "What bounded target and business invariant limit impact?"],
        "scenario": {"scenario": "Synthetic case: a runbook sees a payment timeout and retries the charge endpoint without checking the order idempotency key or payment state.", "impact": "The retry could create duplicate payment or fulfillment; the scenario does not assert that a duplicate occurred.", "constraints": "At most one fulfillment per order; no secret values in logs; the automation must stop when payment state cannot be determined.", "facts": "Synthetic input: order `BL-204`; first call timed out after 3 seconds; response status is unknown; no reconciliation result is supplied.", "inference": "A timeout alone cannot distinguish a committed operation from a lost response. The duplicate risk follows only if the retry is not deduplicated and the first action committed.", "root": "Potential defect: retry policy equates timeout with failure → does not query authoritative payment/order state → repeats a non-idempotent action.", "diagnostic_steps": ["Record order ID and correlation ID; never record credentials or payment secrets.", "Check the runbook's retry condition and whether it treats timeout as unknown.", "Inspect whether the idempotency key is stable across attempts and scoped to the order.", "Require reconciliation evidence before any second write; record unknown if evidence is absent.", "Check max attempts, timeout, target allowlist, permissions, and audit output."], "fix": "Make the runbook read-only until state reconciliation completes. Reuse a stable idempotency key, query authoritative payment and order state, require an operator checkpoint for ambiguity, and verify one fulfillment after recovery.", "verify": "Replay the synthetic timeout decision on paper: if commit state is unknown, expected result is STOP and escalate; if a matching payment and order exist, do not retry; if authoritative state proves no commit, a bounded retry may proceed under approval.", "residual": "A state query may lag or be unavailable. Automation should stop on stale/ambiguous evidence and hand off rather than assume absence.", "diagram": ("Payment request times out", "Timeout treated as definite failure", "Blind retry may duplicate side effect", "Reconcile state; stable idempotency key", "Stop if unknown; verify one fulfillment")},
        "lab": {"name": "Safe runbook decision table", "goal": "Design a bounded decision procedure for payment timeout recovery.", "expected": "A runbook worksheet that stops safely on ambiguous state and preserves one fulfillment.", "mode": "local tabletop; no endpoint, payment, or fault injection", "prereq": "Basic understanding of retry and idempotency; bring Day 129 runbook/pipeline evidence if available", "preflight": "Use synthetic order BL-204 only. No payment credentials or live API calls.", "steps": eight_steps("runbook", "order=BL-204; first payment call=timeout after 3s; commit state=unknown; retry count=0", "write decision branches for state=committed, state=not committed, and state=unknown; stable key=BL-204", "unknown→STOP/escalate; committed→do not retry; not committed→one approved bounded retry", "state lookup unavailable; expected action is STOP and page payment owner", "Record the invariant check, max attempts=1 after proof of non-commit, and no-secret logging rule."), "file": "day-130-topic-04-runbook.md", "verification": "Acceptance check: every state has one action; unknown state cannot reach a write; all writes have stable idempotency key, bound, owner, and verification.", "accept": "Save the decision table, permissions/scope assumptions, and escalation rule in `day-130-topic-04-runbook.md`.", "trouble": "If a state cannot be established, keep it unknown; do not reinterpret timeout as failure. Remove secrets from any copied examples.", "cleanup": "No automation runs and no resources are created. Retain only the local runbook artifact."}
    },
    {
        "key": "topic-05", "title": "Service catalog and self-service provisioning",
        "overview": "A service catalog presents supported offerings with purpose, owner, service boundary, approved inputs, provisioning path, support model, lifecycle, and evidence. Self-service shifts request execution closer to users while platform teams encode safe defaults and constraints in templates, policy, permissions, and validation. A catalog listing is discovery and governance; it does not itself guarantee the deployed resource is secure, supported, or cleaned up. Link each entry to a versioned template or pipeline, an owning team, support contacts, and lifecycle guidance. This packages the proven baseline as the day's practice. A developer chooses an unsupported region or oversized shape because the offering description omits constraints. The resulting deployment raises cost and support effort while weakening compliance.",
        "preview": "A self-service request accepts a region and machine size outside the tested baseline. The platform team cannot support the resulting workload and the product team inherits an avoidable cost or compliance issue.",
        "technical": "Treat a catalog item as a contract around a provisioning workflow: discover → select supported parameters → validate identity and policy → invoke an approved versioned template/pipeline → emit resource and ownership metadata → hand over runbook and lifecycle path. The product owner defines workload requirements and consumes the service; the platform owner maintains the template, guardrails, and support boundary; the approver handles exceptions. Inputs should be typed, bounded, and defaulted; reject unsupported combinations with a clear reason. Catalog visibility must align with permissions: discoverability is not authorization. Versioning needs a migration/deprecation policy and a way to identify deployed instances. Include support tier, SLO boundary, owner labels, cost tags, data classification, backup expectations, and retirement steps. Trade-off: a narrow paved road simplifies support and compliance but may not fit every workload; exceptions need explicit risk owner, expiry, and migration path.\n\nA catalog record should distinguish what the platform promises from what the workload team remains responsible for. Revalidate links, templates, permissions, supported regions, and lifecycle steps whenever the offering changes.",
        "reference": "https://docs.cloud.google.com/service-catalog/docs/terraform-configuration", "reference_label": "Google Cloud Service Catalog: create a Terraform configuration (accessed 2026-09-29)",
        "questions": ["Which input fields are supported and how are out-of-range values rejected?", "Does catalog visibility align with deployment permissions?", "Who maintains, supports, versions, and retires the offering?"],
        "scenario": {"scenario": "Synthetic case: a Brightloaf developer uses a self-service baseline template, but its entry omits allowed regions, owner labels, support boundary, and retirement workflow.", "impact": "The deployment may be unowned, outside the tested support envelope, or left running after the project ends. No live deployment is asserted.", "constraints": "Only the proven baseline is offered; users cannot silently bypass policy; the exit artifact links the IaC/pipeline evidence and names the service owner.", "facts": "Synthetic input: approved regions are `asia-south1` and `us-central1`; allowed shapes are `small` and `medium`; required labels are `service`, `owner`, and `environment`; lifecycle review is every 90 days.", "inference": "Missing catalog metadata could permit invalid requests or delay support. Confirm by comparing catalog fields, template schema, IAM, organization policy, and resulting inventory.", "root": "Potential chain: catalog entry is only descriptive → parameters are not constrained in workflow → unsupported deployment is accepted → ownership and lifecycle evidence are missing at handoff.", "diagnostic_steps": ["Compare catalog description and supported inputs with the actual template schema and pipeline validation.", "Check the allowed regions and shapes against the supplied synthetic policy list.", "Verify required labels and identify which stage enforces them.", "Distinguish catalog visibility from IAM permission to provision.", "Trace version, owner, support path, review date, and retirement procedure into the entry."], "fix": "Publish a versioned offering that exposes only approved region/shape choices, enforces required labels and policy in the provisioning workflow, names platform and workload owners, links IaC/pipeline evidence, and states support, review, and retirement responsibilities.", "verify": "Reject `europe-west1` and `large`; accept a supported pair such as `asia-south1` plus `small`; confirm required labels, owner, template version, support contact, and 90-day review are present in the catalog record. These are tabletop checks, not live validation.", "residual": "Catalog metadata can drift from deployed templates and policies. Reconcile entries against versions and inventory; require an explicit exception path with owner and expiry.", "diagram": ("Developer selects offering", "Inputs and ownership contract are missing", "Unsupported or unowned deployment", "Constrain schema and link versioned pipeline", "Accepted inputs carry owner and lifecycle")},
        "lab": {"name": "Supported platform offering catalog entry", "goal": "Package the baseline as a supported offering with constrained inputs and clear ownership.", "expected": "A catalog entry, responsibility matrix, and IaC/pipeline evidence link that rejects unsupported inputs.", "mode": "local tabletop; no service catalog or resources are provisioned", "prereq": "Day 129 proven pipeline and Day 81 baseline artifacts; record unavailable artifacts as a gap", "preflight": "Use the supplied synthetic allowlists only. Do not create a Google Cloud catalog or project.", "steps": eight_steps("catalog", "regions=[asia-south1,us-central1]; shapes=[small,medium]; required labels=[service,owner,environment]; review=90 days", "author catalog fields: purpose, owner, boundary, supported inputs, template version, support, lifecycle, evidence link", "accept asia-south1+small; reject europe-west1 and large; require all three labels", "request region=europe-west1 and shape=large; mark validation=reject before provisioning", "Close with catalog entry, responsibility matrix, linked IaC/pipeline evidence, and lifecycle review date. Link the delivered evidence at [Day 129 pipeline evidence](../days/day-129.html#topic-02-lab); if the original Day 129 artifact itself was not supplied, record that evidence as unavailable instead of inserting a placeholder."), "file": "day-130-topic-05-catalog.md", "verification": "Acceptance check: entry names product/platform owners and boundary, exact allowlists, rejection reasons, template/pipeline version, support path, required labels, review date, retirement steps, and a link to the Day 129 pipeline evidence.", "accept": "Save the catalog entry and operating responsibility matrix in `day-130-topic-05-catalog.md`; link the Day 129 pipeline evidence at [Day 129 pipeline evidence](../days/day-129.html#topic-02-lab). If its source artifact was not supplied, state that directly and do not claim the linkage is complete.", "trouble": "If the template allows a value that the catalog calls unsupported, treat the offering as inconsistent and block release until the schema/policy is aligned.", "cleanup": "No provisioning occurred. Keep the local catalog artifact and record cloud cleanup as not applicable."}
    }
]

DATA = {
    "day": 130,
    "part1_intro": "Day 130 turns the proven platform baseline into a supported service. The operating contract must say who owns the customer outcome, what the platform provides, how changes are governed, how incidents are coordinated, which actions can be automated, and how users request a supported configuration. Use the supplied Brightloaf cases as synthetic scenarios and connect the exit evidence to the real Day 129 IaC and pipeline artifacts when available.",
    "exit_summary": "A catalog entry and operating responsibility matrix linked to the IaC/pipeline evidence, including service boundary, supported inputs, owners, change and incident paths, runbook limits, verification, and lifecycle responsibilities.",
    "part2_intro": "The service path below traces request ownership through platform controls, release governance, incident response, and cataloged provisioning. It is a conceptual operating model, not a deployed topology or proof that a team has these controls.",
    "arch_table_html": """<div class=\"table-container\"><table><thead><tr><th>Service path / owner</th><th>Control and boundary</th><th>Observable evidence</th><th>Trade-off / limit</th></tr></thead><tbody>
<tr><td>Product service outcome — product team</td><td>Own service SLO, application behavior, data semantics, and customer-impact decisions</td><td>Service inventory, named on-call, error/latency signals, order/payment invariants</td><td>Autonomy needs shared platform guardrails and clear escalation when dependencies fail</td></tr>
<tr><td>Shared platform — platform team</td><td>Own supported runtime, identity, policy, reusable pipeline, and platform SLO boundary</td><td>Versioned IaC/pipeline, policy results, platform incident signals</td><td>Central consistency can add queue time; self-service requires constrained inputs</td></tr>
<tr><td>Release/change — service owner and approver</td><td>Risk-based approval, immutable artifact, staged exposure, health gate, rollback/forward recovery</td><td>Change ID, digest, cohort, two-window health evidence, decision timestamp</td><td>Canary reduces blast radius but may miss rare paths or delayed symptoms</td></tr>
<tr><td>Incident/problem — incident commander and technical owners</td><td>Coordinate live recovery; link causal learning and approved corrective change</td><td>Canonical timeline, roles, customer update, invariant check, owned follow-ups</td><td>Process overhead is useful only when impact/complexity warrants structured roles</td></tr>
<tr><td>Catalog/provisioning — platform publishes, product consumes</td><td>Expose supported templates and typed allowlists; enforce policy at provisioning boundary</td><td>Catalog version, owner labels, pipeline link, support and retirement path</td><td>Catalog discovery is not authorization or proof of deployed compliance</td></tr>
</tbody></table></div>""",
    "arch_diagram": {
        "type": "topology", "title": "Day 130 service ownership and catalog operating path",
        "desc": "A service request flows through catalog constraints, platform provisioning, product ownership, release gates, incident coordination, and verified lifecycle evidence.",
        "caption": "Figure 130.1. Conceptual ownership and control path for a supported platform offering; it does not prove current team assignments, deployed permissions, live telemetry, or implementation behavior.",
        "width": 1050, "height": 540,
        "layers": [
            {"name": "LAYER 1: USER REQUEST AND CATALOG CONTRACT", "desc": "Supported offering, constrained inputs, owner and lifecycle metadata", "y": 10, "h": 80, "stroke": "#38bdf8", "fill": "#0c1e38", "title_color": "#38bdf8"},
            {"name": "LAYER 2: PLATFORM PROVISIONING AND POLICY BOUNDARY", "desc": "Versioned IaC/pipeline, identity, policy validation and audit", "y": 105, "h": 80, "stroke": "#818cf8", "fill": "#141838", "title_color": "#818cf8"},
            {"name": "LAYER 3: PRODUCT SERVICE AND RELEASE CONTROL", "desc": "Service team owns application outcome; governed staged changes", "y": 200, "h": 80, "stroke": "#22c55e", "fill": "#072417", "title_color": "#22c55e"},
            {"name": "LAYER 4: INCIDENT COORDINATION AND SAFE AUTOMATION", "desc": "Named response roles, bounded runbook action and invariant check", "y": 295, "h": 80, "stroke": "#f59e0b", "fill": "#261a08", "title_color": "#f59e0b"},
            {"name": "LAYER 5: EVIDENCE, FOLLOW-UP AND LIFECYCLE", "desc": "Change and incident records linked to review, support, and retirement", "y": 390, "h": 80, "stroke": "#f43f5e", "fill": "#2a0a14", "title_color": "#f43f5e"}],
        "components": [
            {"name": "Service Catalog", "detail": "Supported inputs + named owner", "x": 60, "y": 25, "w": 250, "h": 48, "stroke": "#38bdf8", "fill": "#0e294b"},
            {"name": "Request Validation", "detail": "Reject outside allowlists", "x": 400, "y": 25, "w": 250, "h": 48, "stroke": "#38bdf8", "fill": "#0e294b"},
            {"name": "Versioned IaC/Pipeline", "detail": "Policy + audit boundary", "x": 60, "y": 120, "w": 250, "h": 48, "stroke": "#818cf8", "fill": "#191c4d"},
            {"name": "Platform Owner", "detail": "Shared runtime and controls", "x": 400, "y": 120, "w": 250, "h": 48, "stroke": "#818cf8", "fill": "#191c4d"},
            {"name": "Product Service", "detail": "Customer SLO + data", "x": 60, "y": 215, "w": 250, "h": 48, "stroke": "#22c55e", "fill": "#0b3824"},
            {"name": "Release Gate", "detail": "Canary + pause/rollback", "x": 400, "y": 215, "w": 250, "h": 48, "stroke": "#22c55e", "fill": "#0b3824"},
            {"name": "Incident Roles", "detail": "Commander + technical leads", "x": 60, "y": 310, "w": 250, "h": 48, "stroke": "#f59e0b", "fill": "#38230a"},
            {"name": "Bounded Runbook", "detail": "Preconditions + invariant", "x": 400, "y": 310, "w": 250, "h": 48, "stroke": "#f59e0b", "fill": "#38230a"},
            {"name": "Linked Evidence", "detail": "Change / incident / owner", "x": 60, "y": 405, "w": 250, "h": 48, "stroke": "#f43f5e", "fill": "#3d101d"},
            {"name": "Review + Retirement", "detail": "Support and lifecycle", "x": 400, "y": 405, "w": 250, "h": 48, "stroke": "#f43f5e", "fill": "#3d101d"}],
        "flows": [
            {"x1": 310, "y1": 49, "x2": 400, "y2": 49, "label": "Validate request", "type": "ok"},
            {"x1": 185, "y1": 73, "x2": 185, "y2": 120, "label": "Invoke version", "type": "ok"},
            {"x1": 310, "y1": 144, "x2": 400, "y2": 144, "label": "Enforce boundary", "type": "ok"},
            {"x1": 185, "y1": 168, "x2": 185, "y2": 215, "label": "Handoff owner", "type": "ok"},
            {"x1": 310, "y1": 239, "x2": 400, "y2": 239, "label": "Stage release", "type": "ok"},
            {"x1": 185, "y1": 263, "x2": 185, "y2": 310, "label": "Coordinate event", "type": "ok"},
            {"x1": 310, "y1": 334, "x2": 400, "y2": 334, "label": "Check invariant", "type": "ok"},
            {"x1": 185, "y1": 358, "x2": 185, "y2": 405, "label": "Record result", "type": "ok"},
            {"x1": 310, "y1": 429, "x2": 400, "y2": 429, "label": "Review lifecycle", "type": "ok"}],
        "probes": [
            {"cx": 60, "cy": 120, "label": "PROBE 1: One accountable owner at each customer boundary", "badge": "P1", "color": "#818cf8"},
            {"cx": 60, "cy": 215, "label": "PROBE 2: Change decision is backed by health and rollback evidence", "badge": "P2", "color": "#22c55e"},
            {"cx": 60, "cy": 405, "label": "PROBE 3: Catalog links to version, support, and retirement evidence", "badge": "P3", "color": "#f43f5e"}]
    },
    "part3_intro": "These are synthetic field cases for causal reasoning, not claims about observed Brightloaf or Google Cloud incidents. Each separates supplied inputs from inference, identifies constraints and evidence to gather, and defines a bounded correction with a verification signal and residual risk.",
    "part4_intro": "Complete each local tabletop as a working artifact. Every topic has exactly eight titled execution stages with fixed inputs, a bounded decision challenge, observable expected results, and an acceptance check after Stage 8. No cloud resources, live incidents, customer messages, or fault injection are part of these labs.",
    "topics": topics
}
