"""Durable Day 3 curriculum specification: DNS, sockets and transport.

All examples are local/tabletop observations. They are not production claims.
"""

DAY_NUM = 3


def lab(name, goal, expected, steps, accept, trouble):
    """Keep the required eight-stage local/tabletop lab shape explicit."""
    return {
        "name": name, "goal": goal, "expected": expected,
        "mode": "local/tabletop; no cloud resources or credentials required",
        "prereq": "Day 2 network-path artifact, a terminal with dig and curl, and a text editor",
        "preflight": "Use only approved public documentation/test names; record local command output as an observation, not as a universal result.",
        "steps": steps, "verification": "Compare the recorded diagram and command transcript with the stated invariant; environment-dependent resolver output is illustrative.",
        "accept": accept, "trouble": trouble,
        "cleanup": "Save only the worksheet/transcript. No cloud resources, DNS records, listeners, or credentials were created.",
        "file": "day-003-dns-transport-evidence.md",
    }


DATA = {
    "day": 3,
    "part1_intro": "Day 3 separates three boundaries that are often conflated: a name resolving to an address, a packet being reachable to that address, and a transport connection becoming established. Build from the Day 2 next-hop artifact and preserve uncertainty where a local resolver, network policy, or remote host is not under your control.",
    "exit_summary": "Produce one annotated DNS/transport diagram that distinguishes IPv4 and IPv6 name resolution, IP reachability, and a TCP established connection; attach answers for record type, resolver role, endpoint, port, and handshake state.",
    "part2_intro": "The path is intentionally layered: addressing supplies a scoped destination, DNS supplies data from an authority through a resolver cache, and transport supplies a socket-to-socket exchange. A successful result at one layer is evidence only for that layer.",
    "arch_table_html": """<div class=\"table-container\"><table><caption>DNS and transport evidence boundaries</caption><thead><tr><th scope=\"col\">Question</th><th scope=\"col\">Control or data path</th><th scope=\"col\">Observable evidence</th><th scope=\"col\">Limit</th></tr></thead><tbody><tr><th scope=\"row\">What IPv6 address may be used?</th><td>Host chooses an address and scope; router/NDP applies only where applicable.</td><td>Address notation, prefix length, and chosen interface.</td><td>An address alone does not prove a route or service listener.</td></tr><tr><th scope=\"row\">Who answered the name?</th><td>Stub asks recursive resolver; resolver may answer cache or query authoritative data.</td><td>dig flags, answer section, TTL, and server field.</td><td>A cached answer is not proof that the authoritative zone was queried now.</td></tr><tr><th scope=\"row\">Is a service connection established?</th><td>Client socket selects local endpoint; TCP synchronizes sequence state with server socket.</td><td>Local socket state and bounded packet/connection trace.</td><td>TCP establishment does not prove HTTP authorization or application success.</td></tr></tbody></table></div>""",
    "arch_diagram": {
        "type": "topology", "title": "Day 3 DNS, IPv6, and TCP transport evidence path",
        "desc": "A three-tier topology separating client addressing, recursive and authoritative DNS roles, and transport connection evidence.",
        "caption": "Scope: a local/tabletop request journey from name lookup to a TCP socket. It does not prove Internet reachability, a remote application's health, or a production incident.",
        "width": 1120, "height": 690,
        "layers": [
            {"name": "TIER 1 · INGRESS / DEMAND", "desc": "client name and destination choice", "x": 20, "y": 55, "w": 1080, "h": 92, "fill": "#1e3a5f", "title_color": "#7dd3fc"},
            {"name": "TIER 2 · RUNTIME / DATA", "desc": "resolver data and socket exchange", "x": 20, "y": 185, "w": 1080, "h": 210, "fill": "#064e3b", "title_color": "#6ee7b7"},
            {"name": "TIER 3 · GOVERNANCE / DECISION", "desc": "evidence classification and stop conditions", "x": 20, "y": 435, "w": 1080, "h": 115, "fill": "#422006", "title_color": "#fdba74"},
        ],
        "components": [
            {"x": 65, "y": 88, "w": 230, "h": 45, "name": "Dual-stack client", "detail": "stub resolver + socket", "stroke": "#38bdf8"},
            {"x": 430, "y": 88, "w": 250, "h": 45, "name": "Requested DNS name", "detail": "A / AAAA question", "stroke": "#38bdf8"},
            {"x": 815, "y": 88, "w": 220, "h": 45, "name": "Destination policy", "detail": "scope and route choice", "stroke": "#38bdf8"},
            {"x": 65, "y": 225, "w": 230, "h": 60, "name": "Recursive resolver", "detail": "cache or recursion", "stroke": "#22c55e"},
            {"x": 430, "y": 225, "w": 250, "h": 60, "name": "Authoritative zone", "detail": "RRset + TTL", "stroke": "#22c55e"},
            {"x": 815, "y": 225, "w": 220, "h": 60, "name": "Server socket", "detail": "IP address + port", "stroke": "#22c55e"},
            {"x": 260, "y": 322, "w": 260, "h": 52, "name": "TCP state machine", "detail": "SYN · SYN-ACK · ACK", "stroke": "#f59e0b"},
            {"x": 650, "y": 322, "w": 260, "h": 52, "name": "UDP datagram path", "detail": "no connection state", "stroke": "#f59e0b"},
            {"x": 190, "y": 468, "w": 280, "h": 58, "name": "Evidence worksheet", "detail": "resolution ≠ reachability", "stroke": "#fdba74"},
            {"x": 650, "y": 468, "w": 280, "h": 58, "name": "Stop condition", "detail": "label unknown cause", "stroke": "#fdba74"},
        ],
        "flows": [
            {"x1": 295, "y1": 110, "x2": 430, "y2": 110, "label": "query", "type": "ok"}, {"x1": 680, "y1": 110, "x2": 815, "y2": 110, "label": "candidate", "type": "ok"},
            {"x1": 180, "y1": 133, "x2": 180, "y2": 225, "label": "DNS", "type": "ok"}, {"x1": 555, "y1": 133, "x2": 555, "y2": 225, "label": "delegation", "type": "ok"}, {"x1": 925, "y1": 133, "x2": 925, "y2": 225, "label": "destination", "type": "warn"},
            {"x1": 555, "y1": 285, "x2": 390, "y2": 322, "label": "answer", "type": "ok"}, {"x1": 815, "y1": 255, "x2": 520, "y2": 348, "label": "TCP", "type": "ok"}, {"x1": 780, "y1": 285, "x2": 780, "y2": 322, "label": "UDP", "type": "warn"},
            {"x1": 390, "y1": 374, "x2": 390, "y2": 468, "label": "record", "type": "ok"}, {"x1": 470, "y1": 497, "x2": 650, "y2": 497, "label": "classify", "type": "ok"},
        ],
        "boundaries": [{"x": 40, "y": 425, "w": 1040, "h": 135, "label": "VERIFICATION BOUNDARY · EACH OBSERVATION IS LIMITED TO ITS LAYER", "color": "#f59e0b"}],
        "probes": [{"cx": 290, "cy": 225, "label": "P1: DNS answer and TTL", "color": "#38bdf8"}, {"cx": 925, "cy": 285, "label": "P2: socket endpoint", "color": "#22c55e"}, {"cx": 910, "cy": 374, "label": "P3: state evidence", "color": "#f59e0b"}],
    },
    "part3_intro": "These are synthetic Brightloaf tabletop cases. The quoted command outputs are illustrative local evidence formats, not records of a real production event; each diagnosis preserves the distinction between an observed symptom and an architectural inference.",
    "part4_intro": "The exercises use supplied or local resolver output only. Do not alter DNS zones, firewall rules, routes, or remote services. Save the diagram and answers as an evidence artifact.",
    "topics": [
        {
            "key": "topic-01", "title": "IPv6 addressing and scope",
            "overview": "IPv6 represents a 128-bit address, normally written as hexadecimal groups, with a prefix length that identifies the network portion. Scope matters: link-local addresses require an interface context, while a global-looking address still needs a usable route and a listening service before it can support an application exchange.",
            "preview": "A client has an AAAA answer but attempts a link-local destination without an interface scope. The user experiences an apparent name-resolution success followed by no usable connection.",
            "technical": "#### Address, prefix, and scope\n\nAn IPv6 address is not a route. A host selects a source and next hop according to local interface, addressing, and routing information; Neighbor Discovery replaces IPv4 ARP functions on IPv6 links. Link-local addresses are valid only on their link, so a socket destination may need a zone/interface identifier in local tooling.\n\n- **Control boundary:** interface configuration, prefix and route selection are local network controls.\n- **Data path:** a DNS AAAA answer supplies an address record; packets still require a source address, route, next-hop resolution, and a receiver.\n- **Failure signal:** an AAAA response or a formatted address alone cannot establish which path failed.\n- **Trade-off:** dual stack improves compatibility but creates independent IPv4 and IPv6 paths that must be tested and evidenced separately.\n\n**Evidence limit:** supplied resolver text can show a record; a local IPv6 route-table observation can show a route on that host; neither proves behavior from another network.",
            "questions": ["Which scope and interface make this IPv6 destination meaningful?", "What evidence separates an AAAA answer from route reachability?", "When is an IPv4 fallback a compatibility choice rather than proof that IPv6 is broken?"],
            "reference": "https://datatracker.ietf.org/doc/html/rfc4291#section-2", "reference_label": "RFC 4291 §2: IPv6 addressing architecture (accessed 2026-09-30)",
            "scenario": {"scenario": "Synthetic tabletop: Brightloaf's test client receives an AAAA record for a service and an operator copies a link-local address into a runbook without its interface context.", "impact": "Supplied symptom: the lookup is recorded as successful while the follow-on connection cannot identify a usable destination. Business impact is a delayed test, not a claimed production outage.", "constraints": "Do not modify network configuration or claim a remote service failure; use the supplied output and local route table only.", "evidence": "```text\n$ dig AAAA api.example.test\n;; ANSWER SECTION:\napi.example.test. 300 IN AAAA 2001:db8:1::20\n\n$ ip -6 route\nfe80::/64 dev eth0 proto kernel metric 256\n```\nThis is illustrative local evidence.", "root": "Architectural inference: the runbook confused a DNS record with a scoped, routed socket destination. The supplied documentation prefix is also reserved for examples and must not be treated as a live target.", "diagnostic_steps": ["Label the AAAA answer as name-resolution evidence only.", "Record the destination scope and the local interface/route separately.", "Check whether the test target and socket endpoint are supplied or locally observable.", "Stop at an unknown route or listener rather than assigning an application cause."], "remediation_steps": ["Store address, prefix, scope, and interface as separate runbook fields.", "Require a two-path worksheet: AAAA resolution plus a bounded local route observation."], "verify": "A reviewer can point to distinct fields for DNS answer, chosen interface, route evidence, and TCP state; no field claims that another field proves it.", "residual": "Local routes and remote policy can change after the worksheet is made; repeat observations when the environment changes.", "diagram": ("AAAA lookup returns address", "address treated as reachable endpoint", "connection test is misclassified", "record scope and route separately", "diagram labels resolution and reachability"), "facts": "Synthetic supplied resolver and route snippets.", "inference": "The failure is a documentation/evidence-boundary defect, not proof of a network outage.", "expected": "The next test stops at the first unproven boundary."},
            "lab": lab("Build an IPv6 scope worksheet", "Separate IPv6 notation, scope, resolver answer, and route evidence.", "One annotated IPv6 branch with an explicit unknown/stop condition where evidence is absent.", ["Stage 1 — Preflight: write `2001:db8:1::20/64` and `fe80::1` in the worksheet; mark the documentation prefix and link-local scope.", "Stage 2 — Prepare inputs: copy the supplied AAAA response and local IPv6 route-table output into two labeled columns.", "Stage 3 — Author analysis: draw client → AAAA answer → selected interface → route → server socket, leaving a blank only for unobserved evidence.", "Stage 4 — Execute bounded observation: run <kbd>ip -6 addr</kbd> and <kbd>ip -6 route</kbd>; record only the local interface and route lines relevant to the worksheet.", "Stage 5 — Inspect result: identify one prefix length, one interface, and whether the supplied address is link-local or documentation/global-formatted.", "Stage 6 — Rehearse edge case: replace the destination with `fe80::1` and state why an interface/zone is required before a local test is meaningful.", "Stage 7 — Diagnose and decide: label the earliest missing proof as DNS, route, neighbor, listener, or unknown; write one next safe observation.", "Stage 8 — Close out: remove copied transient output that contains unrelated local addresses and save the redacted worksheet."], "Artifact contains address/prefix, scope, resolver evidence, route evidence, one stated limitation, and a next-hop/stop decision.", "If the IPv6 route command is unavailable, use supplied output and explicitly mark the local observation unperformed; do not substitute IPv4 output."),
        },
        {
            "key": "topic-02", "title": "DNS records, TTL and resolver roles",
            "overview": "DNS maps names to typed resource records. A recursive resolver serves a client from cache when permitted or follows delegations to authoritative servers; an authoritative server publishes zone data. A TTL constrains caching of an answer but is not a promise about propagation, reachability, or application availability.",
            "preview": "A cache returns an older address until its recorded TTL expires after a planned change. Users may be sent to the previous destination even though the zone data was changed.",
            "technical": "#### Records and roles\n\nA and AAAA records map names to IPv4 and IPv6 addresses. CNAME aliases one name to another; MX, TXT, NS, SOA, and PTR serve mail, text policy, delegation, zone, and reverse-lookup roles. The stub resolver usually asks a recursive resolver; recursive and authoritative are different responsibilities even when an implementation can host both.\n\n- **Control boundary:** zone owner publishes the authoritative data; cache operator controls local resolver behavior; client controls what it queries and records.\n- **Data path:** query → recursive cache or delegation → authoritative answer → TTL-bearing response → client decision.\n- **Failure signal:** NXDOMAIN, SERVFAIL, timeout, or a stale cache answer are different observations requiring different evidence.\n- **Trade-off:** shorter TTL may reduce cache persistence but increases query dependency; it does not make every resolver refresh simultaneously.\n\n**Evidence limit:** `dig` output identifies a responding server and flags in one observation. It does not alone prove which upstream servers were contacted or when every cache will expire.",
            "questions": ["Which role owns the RRset and which role may serve a cached answer?", "What does the displayed TTL prove and not prove?", "How would you avoid calling a DNS result a reachability test?"],
            "reference": "https://www.rfc-editor.org/rfc/rfc1034#section-4.3.1", "reference_label": "RFC 1034 §4.3.1: name-server and resolver behavior (accessed 2026-09-30)",
            "scenario": {"scenario": "Synthetic tabletop: a Brightloaf migration worksheet changes the intended A and AAAA targets, but the test team treats a cached recursive response as proof that the authoritative zone is wrong.", "impact": "Supplied symptom: different test locations show different answers. Operational impact is delayed cutover review; no customer impact or propagation time is asserted.", "constraints": "Use only supplied transcripts and labels; do not edit a public or private DNS zone.", "evidence": "```text\n$ dig www.example.test A\n;; flags: qr rd ra; QUERY: 1, ANSWER: 1\n;; ANSWER SECTION:\nwww.example.test. 120 IN A 192.0.2.44\n;; SERVER: 192.0.2.53#53\n```\nIllustrative output: `ra` indicates recursion available from the responding server.", "root": "Architectural inference: the worksheet lacks resolver-role and TTL fields, so a cache observation is being compared directly with an unobserved authoritative response.", "diagnostic_steps": ["Classify the supplied server as recursive response evidence, not authoritative proof.", "List query name, type, answer, TTL, flags, and responding server.", "Obtain supplied authoritative evidence only if the exercise provides it; otherwise record unknown.", "Compare observations without inventing a propagation interval."], "remediation_steps": ["Add cache-versus-authority columns to the change worksheet.", "Require the cutover decision to cite RR type, answer, TTL, responder, and observation time."], "verify": "The revised worksheet can explain why two answers may differ without declaring either a network failure.", "residual": "Caching behavior and delegation configuration remain environment-dependent and must be observed again during a real, authorized change.", "diagram": ("client asks recursive resolver", "cached result called authoritative", "cutover decision lacks evidence", "record authority, TTL, and cache role", "decision cites bounded DNS evidence"), "facts": "Synthetic dig-style transcript and a supplied migration scenario.", "inference": "Role confusion, rather than a demonstrated authoritative defect, explains the ambiguity.", "expected": "The team defers the claim until the relevant authoritative evidence exists."},
            "lab": lab("Trace resolver roles and TTL", "Classify DNS records and distinguish cache evidence from authority evidence.", "A resolver worksheet containing A, AAAA, CNAME, MX, TXT, NS, SOA, and PTR roles plus one bounded lookup trace.", ["Stage 1 — Preflight: list A, AAAA, CNAME, MX, TXT, NS, SOA, and PTR with a one-line purpose each.", "Stage 2 — Prepare inputs: paste the supplied `dig` response into the worksheet and label query name, type, flags, server, answer, and TTL.", "Stage 3 — Author analysis: draw stub → recursive resolver → authoritative zone and place the supplied answer at the recursive/cache boundary.", "Stage 4 — Execute bounded observation: run <kbd>dig example.com A</kbd> and <kbd>dig example.com AAAA</kbd>; label output as local observation and keep the server field.", "Stage 5 — Inspect result: identify `rd` and `ra` if shown, one TTL, and whether the output itself names an authoritative source.", "Stage 6 — Rehearse edge case: change the worksheet TTL from 300 to 30 and write what this changes about cache permission, plus what it does not prove about simultaneous refresh.", "Stage 7 — Diagnose and decide: for a stale-looking answer, choose cache, authority, reachability, or unknown as the first boundary needing evidence and record why.", "Stage 8 — Close out: redact any internal names or resolver addresses from the saved artifact and retain only approved/supplied examples."], "Artifact lists all eight record types, shows resolver versus authoritative roles, includes a TTL interpretation, and explicitly separates DNS answer evidence from reachability.", "If `dig` is unavailable, use the supplied transcript; do not infer flags or TTL values not present in it."),
        },
        {
            "key": "topic-03", "title": "TCP and UDP, ports, connection states and buffers",
            "overview": "A socket endpoint pairs an IP address with a port. TCP creates ordered, reliable byte-stream state through a handshake and teardown states such as ESTABLISHED and TIME_WAIT; UDP sends independent datagrams without creating a TCP-style connection. Socket buffers absorb bounded send/receive work but do not remove application, network, or peer limits.",
            "preview": "A service name resolves and packets reach the host, but no process is listening on the requested TCP port. The user sees a failed connection even though DNS and IP reachability may be separately healthy.",
            "technical": "#### Socket and transport boundary\n\nA TCP connection is identified by local and remote address/port pairs. The three-way handshake synchronizes state: client SYN, server SYN-ACK, client ACK; only then is the connection established. TIME_WAIT is a TCP state used during connection termination and is not an application error by itself. UDP has ports and checksum/datagram semantics but no built-in connection establishment, ordering, or retransmission equivalent to TCP's stream behavior.\n\n- **Control boundary:** the operating system owns socket state and buffer limits; the application owns port binding, protocol expectations, and backpressure behavior.\n- **Data path:** DNS answer → route → destination address → transport port → process socket → application protocol.\n- **Failure signal:** refused, timeout, reset, and an application response are distinct signals; they must not be collapsed into a generic “network down.”\n- **Trade-off:** TCP adds ordered delivery and congestion/retransmission behavior; UDP leaves reliability and ordering decisions to the application.\n\n**Evidence limit:** a local `ss` listing can show local socket state. It cannot prove a remote process's state or an application's semantic success.",
            "questions": ["Which five-tuple fields identify the observed TCP flow?", "What fact distinguishes connection establishment from an application response?", "When is UDP appropriate only if the application can tolerate or implement loss/order handling?"],
            "reference": "https://www.rfc-editor.org/rfc/rfc9293", "reference_label": "RFC 9293: Transmission Control Protocol (accessed 2026-09-30)",
            "scenario": {"scenario": "Synthetic tabletop: a Brightloaf integration test uses the right hostname but labels every failure “DNS” without recording the destination port or TCP state.", "impact": "Supplied symptom: the test report cannot tell a refused port from a timeout or an application-level rejection. The business effect is slower triage, not a claimed outage.", "constraints": "No listener is created and no port scan is performed; use supplied socket-state examples and a bounded local observation.", "evidence": "```text\nState      Recv-Q Send-Q Local Address:Port Peer Address:Port\nESTAB      0      0      192.0.2.10:51524  192.0.2.44:443\nTIME-WAIT  0      0      192.0.2.10:51525  192.0.2.44:443\n```\nIllustrative state output; documentation addresses are not live targets.", "root": "Architectural inference: the test evidence skipped the socket endpoint and state transition, collapsing name resolution, IP delivery, transport establishment, and application behavior into one unsupported cause.", "diagnostic_steps": ["Record local and remote address/port separately.", "Place SYN, SYN-ACK, and ACK before ESTABLISHED in the diagram.", "Classify a supplied result as refused, timeout, reset, established, or application response only when the evidence states it.", "Treat buffer pressure as a bounded queue/backpressure question, not proof that packets were lost."], "remediation_steps": ["Use a four-layer triage form: DNS, route, transport state, application protocol.", "Require a destination port and a state/result field before assigning an owner."], "verify": "A reviewer can locate the endpoint pair, handshake, state, and evidence boundary without calling a TCP state an application result.", "residual": "NAT, firewall, load balancer, and remote application behavior can still obscure a path; the form records that uncertainty.", "diagram": ("client uses name and port", "port/state evidence omitted", "all failures blamed on DNS", "record endpoint and handshake state", "triage distinguishes four layers"), "facts": "Synthetic socket-state listing and supplied integration-test scenario.", "inference": "The ambiguity is created by missing transport evidence.", "expected": "The next test names the first failing layer or retains unknown."},
            "lab": lab("Label socket endpoints and handshake", "Draw the TCP handshake, contrast UDP, and identify the boundary between transport and application evidence.", "A DNS/transport diagram with IPv4 and IPv6 lookup branches, endpoint pairs, SYN/SYN-ACK/ACK, ESTABLISHED, and an explicit evidence limit.", ["Stage 1 — Preflight: write the endpoint template `local-IP:local-port → remote-IP:remote-port` and state that port identifies the transport endpoint, not the application outcome.", "Stage 2 — Prepare inputs: use supplied IPv4 `192.0.2.44`, IPv6 `2001:db8:1::20`, remote port 443, and local port 51524 as documentation-only values.", "Stage 3 — Author analysis: draw separate DNS A and AAAA branches that converge only after a selected destination is paired with port 443.", "Stage 4 — Execute bounded observation: run <kbd>ss -tan</kbd> if available and copy at most one locally relevant TCP state line; otherwise retain the supplied state line.", "Stage 5 — Inspect result: label SYN, SYN-ACK, ACK, ESTABLISHED, and TIME_WAIT in order; circle the evidence that proves only TCP establishment.", "Stage 6 — Rehearse edge case: replace TCP with UDP in the diagram and list the absent handshake plus one reliability/ordering responsibility shifted to the application.", "Stage 7 — Diagnose and decide: classify each supplied result as DNS answer, route evidence, TCP state, application response, or unknown; choose one next bounded observation.", "Stage 8 — Close out: remove any unrelated local endpoints from the artifact and save the final diagram with its evidence-limit note."], "Artifact is the required DNS/transport diagram: it visibly distinguishes name resolution, reachability, established TCP connection, endpoint ports, UDP contrast, and what remains unproven.", "If `ss` is unavailable or permissions restrict it, do not install tools or elevate privileges; use the illustrative supplied state output and mark the limitation."),
        },
    ],
}
