part1_html = """
<section id="part-1" class="part">
<h2>1 · Topics of the day</h2>

<article id="topic-01-overview" class="topic-card">
<h3>Cloud Router and BGP (dynamic route advertisement, MED, custom advertisements)</h3>
<p>Cloud Router provides a fully distributed, software-defined Border Gateway Protocol (BGP) control plane running directly on Google's Andromeda Software-Defined Network (SDN). In contrast to traditional physical routers or virtual appliances that inspect every payload packet, Cloud Router operates strictly in the control plane: it exchanges dynamic external BGP (eBGP, RFC 4271) routing topology with on-premises peer routers without ever becoming an inline data-plane transit bottleneck. Organizations configure Cloud Router using Google's global Autonomous System Number (ASN 16550) or regional private ASNs, pairing with customer enterprise ASNs across RFC 6996 private ranges (64512–65534). Dynamic route steering is governed through Multi-Exit Discriminator (MED) mechanics, enabling deterministic active/passive failover paths (such as assigning MED 100 to primary Dedicated Interconnect and MED 200 to backup HA VPN). Furthermore, Cloud Router supports Custom Route Advertisements, empowering network architects to advertise summary aggregate prefixes (such as <code>10.0.0.0/8</code>) to conserve on-premises TCAM capacity, announce Private Google Access VIPs (<code>199.36.153.4/30</code> or <code>199.36.153.8/30</code>), and enforce strict prefix quotas against Cloud Router's default limit of 100 learned routes per region while managing BGP keepalive (20s) and hold timer (60s) convergence dynamics.</p>
<p>A primary Dedicated Interconnect circuit flaps during core switch reboot, but asymmetric MED metrics cause return traffic to hit a stateful on-premises firewall that drops unestablished TCP flows. All hybrid API transactions between on-premises payment systems and cloud microservices terminate abruptly for 60 seconds, resulting in $340,000 in dropped checkout transactions during morning rush hour.</p>
<p><a href="#topic-01-technical">Technical discussion →</a> <a href="#topic-01-problem">Real-world problem →</a> <a href="#topic-01-lab">Step-by-step lab →</a></p>
</article>

<article id="topic-02-overview" class="topic-card">
<h3>Private Google Access for on-premises hosts</h3>
<p>Private Google Access (PGA) for on-premises hosts enables enterprise servers, legacy mainframes, and bare-metal database clusters located within private corporate data centers to securely access Google Cloud APIs and managed services—such as Cloud Storage, BigQuery, Cloud KMS, and Artifact Registry—over private Cloud Interconnect or Cloud HA VPN connections without requiring public IPv4 addresses or routing out to the public internet. The architecture functions through specialized DNS integration and dynamic BGP routing: on-premises DNS servers implement conditional forwarding or response policy zones (RPZ) that resolve <code>*.googleapis.com</code> queries to the restricted Google API Virtual IP (VIP) block <code>restricted.googleapis.com</code> (<code>199.36.153.4/30</code>), which is strictly compatible with VPC Service Controls (VPC-SC) perimeters, or the private API VIP block <code>private.googleapis.com</code> (<code>199.36.153.8/30</code>). Cloud Router advertises this <code>/30</code> VIP prefix to on-premises BGP peers via custom route advertisements, establishing a deterministic private route that guides API requests into Google's edge fabric where Andromeda handles wire-speed ingestion, perimeter policy validation, and symmetric return routing without touching public internet transit.</p>
<p>On-premises night-batch analytics nodes attempting to upload compliance records to BigQuery receive DNS answers for Google's public VIPs, attempting to route through an unadvertised default path and failing completely. Daily regulatory reporting fails to transmit before the 06:00 UTC market open, triggering an automatic Tier-1 regulatory audit and $250,000 in statutory late-filing fines.</p>
<p><a href="#topic-02-technical">Technical discussion →</a> <a href="#topic-02-problem">Real-world problem →</a> <a href="#topic-02-lab">Step-by-step lab →</a></p>
</article>

<article id="topic-03-overview" class="topic-card">
<h3>Choosing VPN vs Interconnect (bandwidth, latency, cost, SLA, lead time)</h3>
<p>Designing hybrid cloud connectivity requires a rigorous multi-dimensional trade-off analysis balancing five architectural criteria: bandwidth throughput, latency stability, total cost of ownership, contractual availability SLAs, and deployment lead times. Cloud HA VPN delivers rapid, self-service provisioning in minutes and automated IPsec encryption across the public internet, offering 3 Gbps per tunnel with Equal-Cost Multi-Path (ECMP) horizontal scaling up to 250 Gbps; however, it remains vulnerable to unpredictable public internet routing latency, jitter, and standard internet data egress pricing. Partner Interconnect offers flexible sub-interface bandwidth from 50 Mbps up to 50 Gbps provisioned in hours or days through certified network providers, while Dedicated Interconnect delivers 10 Gbps or 100 Gbps dedicated physical single-mode optical circuits with deterministic sub-millisecond jitter, 99.99% multi-metro dual-region contractual SLAs, and deeply discounted interconnect data egress rates. In addition, hybrid architects must evaluate transport MTU constraints—specifically Cloud VPN's 1440-byte encapsulation limit requiring mandatory TCP MSS clamping versus Interconnect's 1500-byte and 8896-byte Jumbo Frame support—alongside Cloud NAT port allocation formulas to avoid silent packet loss and socket exhaustion during bulk hybrid data transfers.</p>
<p>An unbudgeted enterprise data warehouse backup bursts across an HA VPN gateway, saturating the 3 Gbps tunnel, triggering MTU packet drops, and exhausting Cloud NAT source ports. The hybrid link collapses under 68% packet loss, inflating monthly cloud egress bills by $84,000 and stalling vital customer telemetry updates for 14 hours.</p>
<p><a href="#topic-03-technical">Technical discussion →</a> <a href="#topic-03-problem">Real-world problem →</a> <a href="#topic-03-lab">Step-by-step lab →</a></p>
</article>
</section>
"""
print("Part 1 defined, length:", len(part1_html))
