from pathlib import Path

ROOT = Path('/home/naveen/Documents/GCP/RoadMap/gcp-180day-architect-site')


def page(number: int, main: str) -> str:
    source = ROOT / f'days/day-{number:03}.html'
    original = source.read_text(encoding='utf-8')
    prefix = original.split('<main id="main"', 1)[0]
    suffix = '<footer' + original.split('<footer', 1)[1]
    result = prefix + main + suffix
    source.write_text(result, encoding='utf-8')
    (ROOT / f'content/day-{number:03}-page.html').write_text(result, encoding='utf-8')


DAY153 = r'''<main id="main" class="container day" data-day="153" data-prev="day-152.html" data-next="day-154.html" data-index="../index.html">
<div class="crumb"><a href="../index.html">Roadmap index</a> / <a href="../index.html#block-discovery-cases-and-exam-preparation">Discovery, cases and exam preparation</a> / Day 153 of 180</div>
<section class="hero">
<div class="pills"><span class="pill">DAY 153</span><span class="pill">2.5–3.5 hours</span><span class="pill">tabletop / design</span><span class="pill">Topic 046</span></div>
<h1>Day 153 — EHR Healthcare — defend the design</h1>
<p class="lead"><strong>Outcome:</strong> Compare two migration and recovery designs against the EHR case’s stated requirements, then defend a bounded recommendation with explicit evidence, assumptions, cost drivers and rollback triggers.</p>
<p><strong>Entry prerequisites:</strong> <a href="day-152.html">Day 152</a>; bring the source-linked EHR fact register and unresolved-question list.</p>
<div class="callout success"><strong>Exit artifact</strong><p>A one-page design comparison, ADR, cost assumptions and risk list; update the regulated-workload and migration capstones with transferable lessons.</p></div>
<p class="small">The official exam guide supplies the case context and the learner’s Day 152 register supplies the case facts. Any product choice, price, latency, RTO/RPO or compliance result not present in those artifacts remains a proposal or open question.</p>
</section>
<aside class="toc" aria-label="On this page"><strong>On this page</strong><a href="#part-1">1 · Topics</a><a href="#part-2">2 · Technical discussion</a><a href="#part-3">3 · Problems and solutions</a><a href="#part-4">4 · Labs</a><div class="toc-topic"><span>Compare the candidate architecture against the EHR fact register</span><a href="#topic-01-overview">overview</a> · <a href="#topic-01-technical">discussion</a> · <a href="#topic-01-problem">problem</a> · <a href="#topic-01-lab">lab</a></div></aside>
<section id="part-1" class="part"><h2>1 · Topics of the day</h2>
<article id="topic-01-overview" class="topic-card"><h3>Compare the candidate architecture against the EHR fact register</h3><p><a href="#topic-01-technical">Technical discussion →</a> <a href="#topic-01-problem">Real-world problem →</a> <a href="#topic-01-lab">Step-by-step lab →</a></p>
<p>Today is a design defense, not a product memorization exercise. Start with the EHR case’s stated business, security, migration and recovery constraints. Compare feasible designs at the boundary where a requirement changes the choice: data consistency, integration shape, recovery target, operator skills, auditability or cost.</p>
<p>Keep three labels visible in every row: <strong>supplied fact</strong>, <strong>architectural inference</strong> and <strong>question requiring confirmation</strong>. A polished diagram without that distinction is not defensible evidence.</p></article>
</section>
<section id="part-2" class="part"><h2>2 · Technical discussion</h2>
<article id="topic-01-technical" class="topic-card"><h3>Compare the candidate architecture against the EHR fact register</h3>
<p>The decision begins with a requirements-to-boundary map, not a database name. For every EHR requirement, write the owner, data boundary, failure consequence, acceptance signal and the fact that would change the choice. The official Professional Cloud Architect guide frames case questions around business requirements, migration planning, data movement, security, recovery, cost and trade-offs; it does not prescribe one implementation for every case.</p>
<table><caption>EHR design-defense matrix</caption><thead><tr><th>Decision boundary</th><th>Candidate A</th><th>Candidate B</th><th>Evidence that decides</th><th>Risk if assumed</th></tr></thead><tbody>
<tr><td>Transactional data</td><td>Managed relational service with compatibility-first migration</td><td>Distributed relational service for a changed scale or availability requirement</td><td>Schema features, write ownership, measured migration throughput, stated recovery target</td><td>Choosing distributed storage can add cost and operational complexity without a case requirement.</td></tr>
<tr><td>Application runtime</td><td>Managed Kubernetes for an existing containerized estate</td><td>Managed compute or serverless runtime for a smaller, independently deployable path</td><td>Container dependency, startup profile, network reachability, team skills and deployment evidence</td><td>Assuming Kubernetes is automatically simpler transfers control-plane and platform work to the team.</td></tr>
<tr><td>Hybrid connectivity</td><td>Private hybrid path with explicit routing, DNS and firewall ownership</td><td>Staged data transfer with a temporary, tightly bounded integration path</td><td>Data-movement volume, cutover window, dependency inventory, return-path test</td><td>A green connectivity test may cover only a probe, not the full migration path.</td></tr>
<tr><td>Protection and audit</td><td>Least-privilege identities, customer-managed keys where required, and centralized audit evidence</td><td>Platform defaults plus compensating controls where the case permits them</td><td>Access matrix, key ownership, log retention, sensitive-data boundary and review owner</td><td>Encryption at rest alone does not prove authorization, key custody or usable audit evidence.</td></tr>
<tr><td>Recovery</td><td>Backup/restore with a rehearsed rollback point</td><td>Replicated or failover design with explicit write and reconciliation rules</td><td>Declared RTO/RPO, restore timing, consistency check and failback owner</td><td>A topology diagram does not prove that recovery meets the target.</td></tr>
</tbody></table>
<p>For the migration, separate <em>copy</em>, <em>change capture</em>, <em>validation</em>, <em>cutover</em> and <em>rollback</em>. The acceptance invariant is not “the command completed”; it is that the required records, identities, permissions and business operations reconcile after the transition. If an event can be replayed, retain a durable idempotency key and prove that one order still produces one fulfillment.</p>
<p>For security, trace a real actor through authentication, authorization, network reachability, data access and audit recording. IAM roles, service identities, key access, firewall policy, private API paths and log sinks have different owners. For recovery, state what happens to writes during a partition, what data is authoritative, and who is allowed to declare rollback. Mark any answer that depends on current product limits or pricing for verification before implementation.</p>
<div class="callout"><strong>Worked defense pattern</strong><p>“I prefer Candidate A because the supplied case requires compatibility with an existing relational workload and the fact register shows no cross-region write requirement. Candidate B becomes preferable if the owner confirms a higher availability target or a scale boundary that Candidate A cannot meet. Before approval I need measured migration throughput, restore evidence, the identity matrix and a dated price estimate.” This is stronger than naming a service without a decision rule.</p></div>
<div class="further"><h4>Further study</h4><p><a href="../sources.html#topic-046">Topic 046 source section</a> links to the current Professional Cloud Architect exam guide. Use the <a href="https://services.google.com/fh/files/misc/professional_cloud_architect_exam_guide_english.pdf" rel="noopener noreferrer">official exam guide</a> for the case-study context and architecture objectives; page content and product terminology can change.</p></div>
</article></section>
<section id="part-3" class="part"><h2>3 · Real-world problem and solution</h2>
<article id="topic-01-problem" class="topic-card"><h3>Case · A plausible EHR design fails when the migration window and recovery target are made explicit</h3>
<p><strong>Situation and impact:</strong> A review board receives a diagram that places the EHR workload on a preferred database and runtime, but the proposal does not show the source dependencies, change-capture path, audit owner, restore test or rollback trigger. Reviewers cannot tell which statements came from the case and which were invented by the designer. Approval would turn unknown migration and regulated-data risks into an outage or an unprovable compliance claim.</p>
<p><strong>Constraints:</strong> Preserve the case’s supplied facts; do not add patient data to the lab; keep the design within the team’s demonstrated skills; and do not claim a live RTO, RPO, price, regional property or service limit without evidence.</p>
<p><strong>Diagnosis:</strong> The design optimized for a product label before converting the case into acceptance tests. It also combined availability, backup, replication and audit into one vague “secure and highly available” requirement. That hides the first failing boundary: a missing dependency, an untested restore, an unauthorized service identity or an unreconciled write.</p>
<p><strong>Defensible solution:</strong> Rebuild the proposal as two alternatives. For each, document data ownership, migration sequence, connectivity, access path, key/log ownership, recovery behavior, cost variables, operator work and a rejected option. Select only after the fact register and one changed-constraint test produce a stable choice. The decision must include a pre-cutover acceptance checklist, a rollback authority and a reconciliation result.</p>
<p><strong>Verification and residual risk:</strong> Run a tabletop failure in which the migration is late, the destination is unavailable, or a duplicate event is replayed. Record the first changed signal and the safe stop point. A tabletop result predicts behavior; it does not prove a deployed EHR service, regulatory approval or customer acceptance.</p></article>
</section>
<section id="part-4" class="part"><h2>4 · Step-by-step lab</h2>
<article id="topic-01-lab" class="topic-card lab"><h3>Exercise 1: Defend two EHR migration and recovery designs</h3>
<p><strong>Goal:</strong> Produce a source-linked design defense from the Day 152 fact register, with one selected option, one rejected option, explicit assumptions and a bounded failure rehearsal.</p>
<p><strong>Mode:</strong> local/tabletop with synthetic data; no cloud access or spend. <strong>Prerequisite:</strong> Day 152 fact register and unresolved-question list.</p>
<h4>Exact execution</h4><ol class="execution-grid">
<li><strong>Preflight.</strong> Create a note named <code>day-153-ehr-design-defense.md</code>. Record the date, prior artifact, lab mode, decision owner and “synthetic case data only.” Copy the source URL into the note.</li>
<li><strong>Freeze the input.</strong> Copy the EHR facts from Day 152 into a table with columns <code>claim | source/page or artifact | supplied/inferred/question | owner</code>. Do not fill missing facts with assumptions.</li>
<li><strong>Draft alternatives.</strong> Create Candidate A and Candidate B. For each, fill <code>data | runtime | connectivity | identity | encryption/key | audit | migration | recovery | cost driver | operator skill</code>. Include a credible rejected alternative and the condition that would make it preferable.</li>
<li><strong>Define acceptance.</strong> Add one check for schema/data reconciliation, one for authorization and audit evidence, one for restore/failback, and one for the invariant <code>one order, one fulfillment</code> where the case touches an order path.</li>
<li><strong>Inject a changed constraint.</strong> Choose one: the cutover window is shorter, the destination region is unavailable, the source emits late changes, or the recovery target becomes stricter. Record the first boundary that changes and whether the selected design survives.</li>
<li><strong>Defend and record.</strong> Write a five-sentence recommendation: choice, evidence, rejected option, trigger to revisit and residual risk. Mark every result as observed locally, supplied by the case, or predicted in the tabletop.</li>
<li><strong>Close out.</strong> Save the note and link it from the daily artifact. Update the regulated-workload and migration capstone notes with the reusable decision rule; remove disposable copies and record what still needs authorized testing or customer confirmation.</li>
</ol>
<div class="callout success"><strong>Expected state</strong><p>A one-page comparison and ADR with a selected design, rejected alternative, owner, evidence classification, changed-constraint result, rollback trigger and unresolved questions.</p></div>
<div class="callout caution"><strong>Troubleshooting</strong><p>If both options seem equally good, identify the missing requirement or measurement. If the diagram names a service but not an acceptance signal, replace the name with a testable boundary. Never convert a predicted result into a production claim.</p></div>
<div class="callout"><strong>Artifact acceptance</strong><p>Accept only when another architect can reproduce the decision from the fact register, see why the alternative was rejected, and identify who owns the next verification.</p></div>
<label class="check"><input type="checkbox" data-progress="lab-153-01"> I completed and checked this topic exercise</label></article>
</section>
<section class="completion"><h2>Daily evidence</h2><label class="check"><input type="checkbox" data-progress="read-153"> I read and reviewed the day</label><label class="check"><input type="checkbox" data-progress="artifact-153"> I saved the exit artifact</label></section>
<nav class="pager" aria-label="Day pagination"><a href="day-152.html">← Day 152<small>EHR facts and constraints</small></a><a href="../index.html">All 180 days<small>Browse the roadmap</small></a><a href="day-154.html">Day 154 →<small>Altostrat content and AI requirements</small></a></nav>
<p class="shortcut">Keyboard: P or [ previous · N or ] next · I index</p></main>
'''


DAY154 = r'''<main id="main" class="container day" data-day="154" data-prev="day-153.html" data-next="day-155.html" data-index="../index.html">
<div class="crumb"><a href="../index.html">Roadmap index</a> / <a href="../index.html#block-discovery-cases-and-exam-preparation">Discovery, cases and exam preparation</a> / Day 154 of 180</div>
<section class="hero">
<div class="pills"><span class="pill">DAY 154</span><span class="pill">2.5–3.5 hours</span><span class="pill">tabletop / design</span><span class="pill">Topic 047</span></div>
<h1>Day 154 — Altostrat Media — content and AI requirements</h1>
<p class="lead"><strong>Outcome:</strong> Read the official Altostrat Media case, extract its hybrid content, discovery, summarization, safety and operating requirements, and separate existing platform facts from proposed AI architecture.</p>
<p><strong>Entry prerequisites:</strong> <a href="day-153.html">Day 153</a>, <a href="day-144.html">Day 144</a>; bring their exit artifacts.</p>
<div class="callout success"><strong>Exit artifact</strong><p>A source-linked requirements matrix and an existing-versus-proposed system/data-flow diagram with owners, evidence types and open questions.</p></div>
<p class="small">The case PDF is the source of supplied facts. Service selections, model quality, moderation thresholds, cost, latency and availability are design hypotheses until verified.</p>
</section>
<aside class="toc" aria-label="On this page"><strong>On this page</strong><a href="#part-1">1 · Topics</a><a href="#part-2">2 · Technical discussion</a><a href="#part-3">3 · Problems and solutions</a><a href="#part-4">4 · Labs</a><div class="toc-topic"><span>Read the official case and extract requirements</span><a href="#topic-01-overview">overview</a> · <a href="#topic-01-technical">discussion</a> · <a href="#topic-01-problem">problem</a> · <a href="#topic-01-lab">lab</a></div><div class="toc-topic"><span>Separate content AI capabilities from control and operating requirements</span><a href="#topic-02-overview">overview</a> · <a href="#topic-02-technical">discussion</a> · <a href="#topic-02-problem">problem</a> · <a href="#topic-02-lab">lab</a></div></aside>
<section id="part-1" class="part"><h2>1 · Topics of the day</h2>
<article id="topic-01-overview" class="topic-card"><h3>Read the official case and extract requirements</h3><p><a href="#topic-01-technical">Technical discussion →</a> <a href="#topic-01-problem">Real-world problem →</a> <a href="#topic-01-lab">Step-by-step lab →</a></p><p>Altostrat’s case describes an established media platform, a modernization direction and a set of business and technical requirements. First capture what already exists: GKE, Cloud Storage, BigQuery, Cloud Run functions, on-premises ingestion/archive, mixed identity providers and mixed monitoring. Then capture what the business wants to improve.</p></article>
<article id="topic-02-overview" class="topic-card"><h3>Separate content AI capabilities from control and operating requirements</h3><p><a href="#topic-02-technical">Technical discussion →</a> <a href="#topic-02-problem">Real-world problem →</a> <a href="#topic-02-lab">Step-by-step lab →</a></p><p>Summarization, metadata extraction, harmful-content detection, trend analysis, recommendations and conversational support are capabilities. Auditability, human or editorial review, identity, data lineage, cost controls, hybrid connectivity, deployment, monitoring and rollback are operating requirements around those capabilities.</p></article>
</section>
<section id="part-2" class="part"><h2>2 · Technical discussion</h2>
<article id="topic-01-technical" class="topic-card"><h3>Read the official case and extract requirements</h3>
<p>The official case states that Altostrat has a GKE-based content management and delivery platform; media documents, audio and video are in Cloud Storage; BigQuery is the primary warehouse; Cloud Run functions perform event-driven work such as transcoding, metadata extraction and personalized recommendations. It also states that some ingestion and archival workflows remain on premises, identity uses Google Identity and third-party providers, and observability combines Cloud Monitoring and Prometheus with email alerts.</p>
<table><caption>Supplied facts versus design work</caption><thead><tr><th>Case statement</th><th>Requirement implied by the case</th><th>Design question</th><th>Evidence needed</th></tr></thead><tbody>
<tr><td>GKE delivers the platform</td><td>Containerized workloads must be deployable and operable across the relevant environments.</td><td>Which workloads truly need Kubernetes, and what must remain compatible on premises?</td><td>Workload inventory, dependency map, deployment and failure tests.</td></tr>
<tr><td>Cloud Storage holds diverse media</td><td>Storage must scale while controlling lifecycle and retrieval cost.</td><td>Which assets need hot access, retention, versioning, restore or legal hold?</td><td>Object-size/access distribution, retention policy, restore acceptance and current pricing check.</td></tr>
<tr><td>BigQuery analyzes behavior and demographics</td><td>Analytics must inform content strategy and decisions.</td><td>What events are collected, at what grain, and which data is sensitive?</td><td>Event contract, lineage, access matrix, freshness target and query-cost baseline.</td></tr>
<tr><td>On-premises ingestion/archive remains</td><td>Hybrid data movement must be secure, observable and recoverable.</td><td>Which side owns the source of truth during migration or replay?</td><td>Connectivity path, DNS/routing ownership, transfer reconciliation and rollback plan.</td></tr>
<tr><td>AI must be auditable and explainable</td><td>Generated results need provenance, evaluation and a decision record.</td><td>What is published automatically, what requires review, and how is a decision appealed?</td><td>Prompt/model/version metadata, source references, evaluation set, reviewer outcome and retention rule.</td></tr>
</tbody></table>
<p>The right first diagram has separate paths for source media, derived media, metadata, user events, AI requests and editorial publication. Draw control boundaries around identity, ingestion, processing, model access, review and delivery. A single “AI service” box obscures whether a request is synchronous, queued, replayable, human-approved or allowed to publish.</p>
<div class="further"><h4>Further study</h4><p><a href="../sources.html#topic-047">Topic 047 source section</a> links to the <a href="https://services.google.com/fh/files/misc/v6.1_pca_altostrat_media_case_study_english.pdf" rel="noopener noreferrer">official Altostrat Media case PDF</a>. The case’s supplied facts are the baseline; current product behavior and limits still require current documentation and testing.</p></div>
</article>
<article id="topic-02-technical" class="topic-card"><h3>Separate content AI capabilities from control and operating requirements</h3>
<p>A useful Altostrat design treats AI output as a derived, reviewable artifact rather than an unquestioned replacement for the source media. A typical flow is: ingest and identify the asset; extract audio, video and technical metadata; transcribe or analyze with the selected model; produce a summary, tags or moderation result; attach provenance and confidence; route uncertain or harmful results to review; publish only after the acceptance rule passes; and emit immutable audit evidence.</p>
<table><caption>AI requirement to control mapping</caption><thead><tr><th>Capability</th><th>Control boundary</th><th>Failure to rehearse</th><th>Acceptance signal</th></tr></thead><tbody>
<tr><td>Summarization</td><td>Source asset, transcript/version, model/prompt version, reviewer state</td><td>Summary invents a claim or omits a material qualification.</td><td>Evaluation set meets the declared quality threshold and every output links to source/provenance.</td></tr>
<tr><td>Metadata enrichment</td><td>Schema, confidence, taxonomy owner and update policy</td><td>Incorrect tags make search or recommendations misleading.</td><td>Field-level validation, sampled precision/recall review and rollback of a bad model version.</td></tr>
<tr><td>Harmful-content detection</td><td>Policy, model result, escalation queue and publication gate</td><td>Unsafe content is published, or legitimate content is silently blocked.</td><td>Known test set, threshold review, appeal path and audit trail for each decision.</td></tr>
<tr><td>Recommendations and conversational support</td><td>User identity, consent, retrieval corpus, tool permissions and response logging</td><td>Private data leaks or the assistant takes an unauthorized action.</td><td>Access tests, grounding/citation checks, refusal tests and bounded tool calls.</td></tr>
<tr><td>Trend analysis</td><td>Event definitions, aggregation window, demographic access and retention</td><td>Incomplete or biased events drive a false content decision.</td><td>Freshness, completeness, lineage and decision-owner review.</td></tr>
</tbody></table>
<p>Separate the online path from the batch path. A user-facing assistant may need bounded latency and a safe degraded response; a large media summarization job can be queued, retried and throttled. Both paths need idempotency, dead-letter handling, model/version traceability, cost attribution and a rollback or reprocessing plan. Do not infer that GKE, Cloud Run functions, BigQuery or Cloud Storage automatically supplies these controls.</p>
<div class="callout"><strong>Design rule</strong><p>Every AI result must answer four questions: which source and version produced it, which model and configuration produced it, who or what approved its use, and what happens when it is wrong. If one answer is missing, the result is a draft, not a publication-grade decision.</p></div>
</article></section>
<section id="part-3" class="part"><h2>3 · Real-world problems and solutions</h2>
<article id="topic-01-problem" class="topic-card"><h3>Case 1 · A hybrid content pipeline has no source-of-truth or replay boundary</h3>
<p><strong>Situation and impact:</strong> A media asset is ingested on premises, copied to Cloud Storage, processed for metadata and summarized, then surfaced in search and recommendations. The proposal does not identify the authoritative asset ID or whether derived results can be replayed. A retry can create duplicate catalog entries, while a partial transfer can make analytics disagree with the editorial system.</p><p><strong>Constraints:</strong> Maintain content availability, protect the hybrid boundary, preserve lineage and avoid treating a successful transfer command as proof of reconciliation.</p><p><strong>Diagnosis and solution:</strong> Assign a stable asset ID and version, record source and derived-object checksums, make processing idempotent, and separate transfer acknowledgement from business acceptance. Define the source of truth for each state, a replay window, a dead-letter path and a reconciliation report. Measure freshness, completeness and failed/replayed work.</p><p><strong>Residual risk:</strong> Storage lifecycle and transfer cost, source metadata quality and on-premises failure behavior still require the owner’s data and a current design review.</p></article>
<article id="topic-02-problem" class="topic-card"><h3>Case 2 · AI output is useful but cannot be safely published</h3>
<p><strong>Situation and impact:</strong> An automatically generated summary and harmful-content label are sent directly to the user experience. Reviewers cannot identify the source segment, model version or threshold that produced a decision. A false negative can expose harmful content; a false positive can suppress legitimate journalism; a hallucinated summary can damage trust.</p><p><strong>Constraints:</strong> Support diverse media, keep the service available, give users a useful fallback and retain enough evidence for an appeal or incident review.</p><p><strong>Diagnosis and solution:</strong> Make AI results versioned drafts with provenance, confidence and policy state. Add an evaluation set, threshold ownership, human review for defined classes, refusal/degraded responses, immutable decision logs and a rollback path. Limit assistants to authorized retrieval and tools; do not grant publication authority merely because a model returned a high score.</p><p><strong>Verification and residual risk:</strong> Run a synthetic test set containing benign, ambiguous and disallowed examples. Record quality by class, review time, false positives/negatives and the exact model/configuration. The result is a bounded evaluation, not proof of production safety across all languages or content types.</p></article>
</section>
<section id="part-4" class="part"><h2>4 · Step-by-step labs</h2>
<article id="topic-01-lab" class="topic-card lab"><h3>Exercise 1: Read the official case and extract requirements</h3><p><strong>Goal:</strong> Build a source-linked fact and requirement register for Altostrat without turning proposed services into case facts.</p><p><strong>Mode:</strong> local/tabletop with synthetic data; no cloud access or spend. <strong>Prerequisite:</strong> the official case PDF and Day 153 decision-defense habits.</p><ol class="execution-grid"><li><strong>Preflight.</strong> Create <code>day-154-altostrat-requirements.md</code>. Record the source URL, date, lab mode and synthetic-data boundary.</li><li><strong>Extract.</strong> Create <code>statement | page | fact or requirement | owner | evidence needed</code> columns. Capture the existing GKE, Cloud Storage, BigQuery, Cloud Run functions, on-premises, identity and observability statements.</li><li><strong>Classify.</strong> Split business requirements from technical requirements. Add success measures for availability, cost, freshness, quality, safety, support and auditability without inventing target values.</li><li><strong>Map boundaries.</strong> Draw source media, derived media, metadata, analytics, AI, review, identity and delivery paths. Mark what is existing, proposed, unknown and retired.</li><li><strong>Inject a change.</strong> Remove hybrid connectivity, double storage volume, or require an editorial review gate. Record the first affected boundary, changed signal and a credible alternative.</li><li><strong>Close out.</strong> Save the matrix and link it from the daily artifact. List the questions that need owner confirmation, current product documentation or a bounded test.</li></ol><div class="callout success"><strong>Expected state</strong><p>A fact register and system/data-flow diagram that another architect can trace back to the official case, with proposed design choices visibly separated.</p></div><div class="callout caution"><strong>Troubleshooting</strong><p>If a statement names a technology but not its role, record the role as an inference. If a requirement has no measurable signal, write the question instead of manufacturing a target.</p></div><label class="check"><input type="checkbox" data-progress="lab-154-01"> I completed and checked this topic exercise</label></article>
<article id="topic-02-lab" class="topic-card lab"><h3>Exercise 2: Create a safe AI content decision path</h3><p><strong>Goal:</strong> Turn one Altostrat capability into a bounded, auditable AI workflow with a safe failure mode.</p><p><strong>Mode:</strong> local/tabletop with synthetic media metadata; no model endpoint or cloud spend. <strong>Prerequisite:</strong> the Day 154 requirements matrix.</p><ol class="execution-grid"><li><strong>Choose one path.</strong> Use synthetic input for summarization, metadata enrichment, harmful-content detection, recommendation or conversational support. Record why the path matters to the case.</li><li><strong>Define the contract.</strong> Write <code>asset_id | source version | input fields | model/config version | output schema | confidence | reviewer state | retention | owner</code>.</li><li><strong>Define controls.</strong> State the authorization boundary, provenance link, evaluation set, human-review rule, refusal/degraded response, rollback trigger and cost/freshness signal.</li><li><strong>Inject failure.</strong> Use a missing transcript, low confidence, unsafe label, stale source or unauthorized retrieval request. Record the first changed signal and the safe outcome.</li><li><strong>Accept or reject.</strong> Mark the output draft, reviewable or publishable according to the declared rule. Record one rejected alternative and the condition under which it could become acceptable.</li><li><strong>Close out.</strong> Save <code>day-154-ai-content-decision.md</code>, link it from the daily artifact and state what still requires an evaluation set, security review, data-owner approval or production test.</li></ol><div class="callout success"><strong>Expected state</strong><p>A bounded AI decision path with provenance, versioning, access control, evaluation, human or policy gate, failure behavior and residual-risk owner.</p></div><div class="callout caution"><strong>Troubleshooting</strong><p>A high confidence score is not an explanation. If the source, model/configuration or reviewer state is missing, keep the output in draft status.</p></div><label class="check"><input type="checkbox" data-progress="lab-154-02"> I completed and checked this topic exercise</label></article>
</section>
<section class="completion"><h2>Daily evidence</h2><label class="check"><input type="checkbox" data-progress="read-154"> I read and reviewed the day</label><label class="check"><input type="checkbox" data-progress="artifact-154"> I saved the exit artifact</label></section>
<nav class="pager" aria-label="Day pagination"><a href="day-153.html">← Day 153<small>EHR design defense</small></a><a href="../index.html">All 180 days<small>Browse the roadmap</small></a><a href="day-155.html">Day 155 →<small>Altostrat architecture defense</small></a></nav>
<p class="shortcut">Keyboard: P or [ previous · N or ] next · I index</p></main>
'''


if __name__ == '__main__':
    page(153, DAY153)
    page(154, DAY154)
