from pathlib import Path

ROOT = Path('/home/naveen/Documents/GCP/RoadMap/gcp-180day-architect-site')


def write_page(number: int, body: str) -> None:
    source = ROOT / f'days/day-{number:03}.html'
    original = source.read_text(encoding='utf-8')
    prefix = original.split('<main id="main"', 1)[0]
    suffix = '<footer' + original.split('<footer', 1)[1]
    result = prefix + body + suffix
    source.write_text(result, encoding='utf-8')
    (ROOT / f'content/day-{number:03}-page.html').write_text(result, encoding='utf-8')


def topic_toc(topics):
    return ''.join(
        f'<div class="toc-topic"><span>{title}</span>'
        f'<a href="#topic-{i:02}-overview">overview</a> · '
        f'<a href="#topic-{i:02}-technical">discussion</a> · '
        f'<a href="#topic-{i:02}-problem">problem</a> · '
        f'<a href="#topic-{i:02}-lab">lab</a></div>'
        for i, title in enumerate(topics, 1)
    )


def make_day(number, title, outcome, prerequisites, exit_artifact, topic_data, source_note, mode='tabletop / design'):
    topics = [x['title'] for x in topic_data]
    overview = []
    technical = []
    problems = []
    labs = []
    for i, item in enumerate(topic_data, 1):
        overview.append(
            f'<article id="topic-{i:02}-overview" class="topic-card"><h3>{item["title"]}</h3>'
            f'<p><a href="#topic-{i:02}-technical">Technical discussion →</a> '
            f'<a href="#topic-{i:02}-problem">Real-world problem →</a> '
            f'<a href="#topic-{i:02}-lab">Step-by-step lab →</a></p>{item["overview"]}</article>'
        )
        technical.append(
            f'<article id="topic-{i:02}-technical" class="topic-card"><h3>{item["title"]}</h3>'
            f'{item["technical"]}<div class="further"><h4>Further study</h4><p>{source_note}</p></div></article>'
        )
        problems.append(
            f'<article id="topic-{i:02}-problem" class="topic-card"><h3>{item["problem_title"]}</h3>'
            f'{item["problem"]}</article>'
        )
        labs.append(
            f'<article id="topic-{i:02}-lab" class="topic-card lab"><h3>Exercise {i}: {item["lab_title"]}</h3>'
            f'<p><strong>Goal:</strong> {item["lab_goal"]}</p>'
            f'<p><strong>Mode:</strong> {mode}; <strong>Prerequisite:</strong> bring the previous artifact and use synthetic data only.</p>'
            f'<ol class="execution-grid">{item["steps"]}</ol>'
            f'<div class="callout success"><strong>Expected state</strong><p>{item["expected"]}</p></div>'
            f'<div class="callout caution"><strong>Troubleshooting</strong><p>{item["trouble"]}</p></div>'
            f'<label class="check"><input type="checkbox" data-progress="lab-{number}-{i:02}"> I completed and checked this topic exercise</label></article>'
        )
    return f'''<main id="main" class="container day" data-day="{number}" data-prev="day-{number-1}.html" data-next="day-{number+1}.html" data-index="../index.html">
<div class="crumb"><a href="../index.html">Roadmap index</a> / <a href="../index.html#block-discovery-cases-and-exam-preparation">Discovery, cases and exam preparation</a> / Day {number} of 180</div>
<section class="hero"><div class="pills"><span class="pill">DAY {number}</span><span class="pill">2.5–3.5 hours</span><span class="pill">{mode}</span><span class="pill">Topics {', '.join(dict.fromkeys(x.get('topic_id', '063') for x in topic_data))}</span></div>
<h1>Day {number} — {title}</h1><p class="lead"><strong>Outcome:</strong> {outcome}</p>
<p><strong>Entry prerequisites:</strong> {prerequisites}</p><div class="callout success"><strong>Exit artifact</strong><p>{exit_artifact}</p></div>
<p class="small">Case statements and exam facts are source-linked. Product choices, prices, limits, quality scores and production behavior are proposals or open questions unless the artifact labels them as observed or verified.</p></section>
<aside class="toc" aria-label="On this page"><strong>On this page</strong><a href="#part-1">1 · Topics</a><a href="#part-2">2 · Technical discussion</a><a href="#part-3">3 · Problems and solutions</a><a href="#part-4">4 · Labs</a>{topic_toc(topics)}</aside>
<section id="part-1" class="part"><h2>1 · Topics of the day</h2>{''.join(overview)}</section>
<section id="part-2" class="part"><h2>2 · Technical discussion</h2>{''.join(technical)}</section>
<section id="part-3" class="part"><h2>3 · Real-world problems and solutions</h2>{''.join(problems)}</section>
<section id="part-4" class="part"><h2>4 · Step-by-step labs</h2>{''.join(labs)}</section>
<section class="completion"><h2>Daily evidence</h2><label class="check"><input type="checkbox" data-progress="read-{number}"> I read and reviewed the day</label><label class="check"><input type="checkbox" data-progress="artifact-{number}"> I saved the exit artifact</label></section>
<nav class="pager" aria-label="Day pagination"><a href="day-{number-1}.html">← Day {number-1}<small>Previous day</small></a><a href="../index.html">All 180 days<small>Browse the roadmap</small></a><a href="day-{number+1}.html">Day {number+1} →<small>Next day</small></a></nav><p class="shortcut">Keyboard: P or [ previous · N or ] next · I index</p></main>
'''


def li(label, text):
    return f'<li><strong>{label}.</strong> {text}</li>'


COMMON_SOURCE = '<a href="../sources.html#topic-047">Topic source section</a> and the linked official case or exam material. Record the source date; external documentation and product behavior can change.'


DAY155 = [
    dict(topic_id='047', title='Compare designs for AI-assisted discovery and support',
         overview='<p>Defend an AI-assisted media design using the Day 154 requirements matrix. Compare a grounded retrieval path with a more tightly controlled workflow, and make the choice depend on latency, quality, auditability, hybrid access and operator capability.</p>',
         technical='''<p>Separate the user request path from the content-processing path. A discovery request may retrieve approved metadata and excerpts, assemble a grounded response and return a safe fallback. A summarization or enrichment job can be queued, retried, evaluated and reviewed before publication. The two paths have different latency, retry, cost and failure requirements.</p><table><caption>Altostrat architecture-defense matrix</caption><thead><tr><th>Boundary</th><th>Option A</th><th>Option B</th><th>Decision evidence</th></tr></thead><tbody><tr><td>Retrieval</td><td>Curated index of approved metadata and transcript excerpts</td><td>Direct warehouse or object queries behind a controlled service</td><td>Freshness, access policy, corpus size and measured response path</td></tr><tr><td>AI orchestration</td><td>Managed model endpoint with bounded tools</td><td>Containerized orchestration with explicit model/version controls</td><td>Model availability, skills, audit requirements and rollback mechanism</td></tr><tr><td>Hybrid operation</td><td>Cloud-first path with a private integration boundary</td><td>Portable service contract that can run across cloud and on-premises</td><td>Data locality, connectivity failure behavior and deployment ownership</td></tr><tr><td>Delivery</td><td>Centralized CI/CD with signed artifacts and staged rollout</td><td>Team-owned pipelines with shared policy checks</td><td>Change lead time, evidence quality, separation of duties and toil</td></tr></tbody></table><p>CDN and transcoding can support the case, but they do not solve AI grounding, auditability or review. State the control that prevents a model from retrieving restricted material, taking an unauthorized action or publishing an unreviewed result. Include a model/configuration identifier and a rollback target in every decision record.</p>''',
         problem_title='Case 1 · The fastest AI demo cannot explain or roll back its answers',
         problem='''<p><strong>Situation and impact:</strong> Altostrat connects a conversational assistant directly to a broad content store. The demo is fast, but the team cannot show which source version supported a response, whether a user was authorized to see it, or how to revert a bad prompt/model change. A stale or restricted asset can become an answer or recommendation.</p><p><strong>Diagnosis and solution:</strong> The design optimized the response path before defining corpus boundaries and evidence. Split approved retrieval from source storage, bind each answer to source/version metadata, use bounded tools and add refusal/degraded behavior. Stage model and prompt changes against an evaluation set, then canary and roll back by version.</p><p><strong>Residual risk:</strong> A tabletop can expose control gaps but cannot prove model quality across all media, languages or users. Track the unresolved evaluation and data-owner decisions.</p>''',
         lab_title='Defend two content and AI integration options', lab_goal='Produce an ADR comparing two feasible AI integration options and rehearse one failure in the selected path.',
         steps=''.join([li('Freeze the inputs','Create <code>day-155-altostrat-defense.md</code>; copy the Day 154 requirements and mark facts, inferences and questions.'),li('Draft options','For each option record retrieval boundary, model path, identity, hybrid dependency, CI/CD, storage cost, observability and rollback.'),li('Set acceptance','Define quality, grounding, audit, latency, cost and safe-failure signals. Do not invent target values; write missing targets as questions.'),li('Change a constraint','Make hybrid connectivity unavailable, model quality insufficient or the review queue saturated. Record the first affected boundary and the alternative response.'),li('Defend','Write the choice, rejected option, revisit trigger, owner and residual risk. Link every material claim to the case or a dated test.'),li('Close out','Save the ADR and update the Day 155 artifact index.')]), expected='An ADR with a selected option, rejected alternative, measurable acceptance signals, rollback path and open questions.', trouble='If one option wins only because it names more managed services, return to the requirement and evidence columns; managed does not mean risk-free.')
    ,dict(topic_id='047', title='Auditability, hybrid operations, CI/CD and cost are part of the AI design',
         overview='<p>The architecture is acceptable only when the operating model is acceptable. Include release provenance, identity ownership, cost attribution, storage lifecycle, hybrid incident response and the people who review or reverse AI decisions.</p>',
         technical='''<p>Use a chain of custody for AI changes: source asset or event, transformation, model and prompt/configuration version, output, reviewer or policy decision, publication state and retention. CI/CD should test infrastructure and application changes, scan artifacts, enforce policy and make staged rollback possible. Observability should connect user experience, queue age, model error, data freshness, spend and human-review backlog.</p><p>Cost is a design variable, not a final spreadsheet. Compare hot versus colder media storage, repeated model inference, egress, index refresh, GPU/CPU use, and human review. A low unit price can be defeated by retries, duplicate processing or an over-broad corpus. For hybrid operations, name the on-premises owner, private path, degraded behavior and evidence needed when the link fails.</p><div class="callout"><strong>Defense rule</strong><p>Reject any architecture sentence of the form “AI makes it automatic” unless it names the input, authorization boundary, evaluation, output owner, audit record and safe response to uncertainty.</p></div>''',
         problem_title='Case 2 · A green deployment hides drift and rising inference cost',
         problem='''<p><strong>Situation and impact:</strong> A new model and index refresh are deployed successfully, but response cost and review backlog rise. The pipeline records deployment success without linking the release to model quality, queue age or spend. Hybrid workers run a different configuration than cloud workers.</p><p><strong>Diagnosis and solution:</strong> The release measure was too narrow. Add versioned configuration, environment parity checks, cost and quality gates, queue/backlog alerts, and a canary with rollback. Assign one owner to reconcile cloud and on-premises versions and another to approve content-policy changes.</p><p><strong>Residual risk:</strong> Alerts are evidence, not automatic remediation. Keep a bounded shutdown or traffic-reduction playbook and verify it with synthetic content.</p>''',
         lab_title='Build the operating-evidence row for the chosen design', lab_goal='Connect release, runtime, quality, cost and incident signals to the AI architecture.',
         steps=''.join([li('Inventory','List artifact, model, prompt, index, data, reviewer and deployment versions.'),li('Map signals','For each version identify one success metric, one failure signal, one owner and one rollback action.'),li('Inject drift','Change one model setting or run one worker with an older configuration. Record the first detectable mismatch.'),li('Cost-check','Add the main storage, inference, transfer, retry and human-review cost drivers; flag any current pricing lookup.'),li('Review','Ask whether an incident responder can tell what changed and stop unsafe publication.'),li('Save','Append the operating matrix to the ADR and link it from the exit artifact.')]), expected='A traceable operating matrix that makes AI quality, cost, release and hybrid drift observable.', trouble='If a metric has no decision owner or response, it is a dashboard decoration; assign the owner or remove the claim.')
]


DAY156 = [
    dict(topic_id='048', title='Read the official Cymbal Retail case',
         overview='<p>Cymbal is an online retailer with a large catalog. The official case describes catalog enrichment, conversational commerce and technical-stack modernization over an environment that mixes on-premises and cloud systems, several databases, Kubernetes, file/SFTP and ETL integrations, an existing web application, IVR/call-center workflows and open-source monitoring.</p>',
         technical='''<p>Start with the existing environment, not the desired product. Record the current source for supplier attributes, catalog identity, price/inventory, customer interactions and order entry. Then separate the business outcomes—less manual effort, better discovery, engagement, conversion and lower cost—from technical requirements such as attribute generation, image variation, scale, HITL review, security and compliance.</p><table><caption>Cymbal fact-to-requirement register</caption><thead><tr><th>Supplied case fact</th><th>Requirement</th><th>Boundary to clarify</th><th>Acceptance evidence</th></tr></thead><tbody><tr><td>Supplier data arrives through existing integrations</td><td>Enrich products without losing source authority.</td><td>Identity, schema/version, duplicate and correction handling.</td><td>Reconciled fixture with source and derived fields.</td></tr><tr><td>Several databases and Kubernetes workloads exist</td><td>Modernize without breaking order/catalog dependencies.</td><td>Read/write ownership, compatibility and migration sequence.</td><td>Dependency map and rollback fixture.</td></tr><tr><td>Conversational discovery is desired</td><td>Return relevant products for natural-language requests.</td><td>Inventory freshness, ranking, personalization and access.</td><td>Relevance and authorization test set.</td></tr><tr><td>Associates must approve generated content</td><td>Provide review, edit, approve and reject states before publication.</td><td>Workflow identity, audit and conflict resolution.</td><td>State transition log and rejected-content test.</td></tr></tbody></table>''',
         problem_title='Case 1 · The proposed catalog pipeline erases source authority',
         problem='''<p><strong>Situation and impact:</strong> A generated description overwrites a supplier attribute, while a later supplier correction is treated as a duplicate and discarded. Sales channels diverge and a call-center agent sees different information from the website.</p><p><strong>Diagnosis and solution:</strong> The design lacked stable product/version identities and separated neither source fields nor derived fields. Retain provenance, version updates, define conflict ownership and publish only approved catalog states. Reconcile every channel against the approved version.</p><p><strong>Residual risk:</strong> Synthetic rows cannot prove supplier quality or production-scale throughput. Record the data owner and the test needed before rollout.</p>''',
         lab_title='Extract Cymbal facts and boundaries', lab_goal='Create a source-linked fact register and existing-versus-proposed catalog/data-flow diagram.',
         steps=''.join([li('Open the source','Create <code>day-156-cymbal-facts.md</code>; record the official PDF URL and page for each claim.'),li('Register facts','Capture systems, databases, integrations, actors, business outcomes and technical requirements.'),li('Mark ownership','For product identity, supplier input, generated field, approval state, price, inventory and customer interaction, name the source of truth.'),li('Draw the flow','Show supplier/SFTP or ETL, staging, enrichment, review, publication, search/discovery and order/call-center paths.'),li('Inject an error','Change one supplier attribute, send a duplicate file or reject an image. Record the first changed state and correction path.'),li('Save','Link the fact register and diagram from the daily artifact.')]), expected='A source-linked matrix and diagram that distinguish existing systems, proposed AI, approval boundaries and open questions.', trouble='If a technology appears in the case, do not assume it is the correct replacement; record its current role and the decision still required.')
    ,dict(topic_id='048', title='Capture supplier integration, generated content, discovery and human review',
         overview='<p>Generated attributes, descriptions and images are derived content. They must be validated against category schema, supplier evidence and the approval policy before they update the catalog. Conversational discovery must retrieve from approved product data and must not invent availability, price or product claims.</p>',
         technical='''<p>Use a content state machine such as <code>received → normalized → generated → validated → needs-review → approved/rejected → published</code>. Keep source and derived values separate, attach a product and content version, and make reprocessing idempotent. The review UI needs role separation, diff visibility, rejection reasons and an audit record.</p><p>For discovery, define the query contract, retrieval corpus, ranking signal, inventory/price freshness and safe fallback. A conversational agent can help a user find products, but order creation and inventory claims need authoritative systems and explicit authorization. Image generation needs content-policy, brand and product-identity checks. Measure relevance and business outcomes separately from model fluency.</p><div class="callout"><strong>Acceptance rule</strong><p>No generated field reaches a customer-facing channel without a valid product identity, schema validation, provenance, policy decision and a reversible publication record.</p></div>''',
         problem_title='Case 2 · A helpful shopping assistant makes an unsafe inventory claim',
         problem='''<p><strong>Situation and impact:</strong> A customer asks for a product with a particular feature. Retrieval finds a similar item, but the assistant claims the item is in stock and suitable. The response came from stale catalog text rather than the inventory or product-attribute authority.</p><p><strong>Diagnosis and solution:</strong> Discovery, recommendation, inventory and order authority were conflated. Restrict retrieval to approved content, call authoritative inventory only when needed, show a safe uncertainty response and log the evidence used. Add adversarial and stale-data tests.</p><p><strong>Residual risk:</strong> A relevance score is not a guarantee of factual correctness or conversion. Maintain human review for sensitive categories and measure returns, complaints and correction time.</p>''',
         lab_title='Design the content approval and discovery contract', lab_goal='Create a synthetic approval workflow and a conversational-discovery acceptance checklist.',
         steps=''.join([li('Create fixtures','Use synthetic supplier rows, one duplicate, one malformed attribute, one generated image and one stale inventory row.'),li('Define schema','Write product ID, source version, derived value, confidence, reviewer, state, rejection reason and publication timestamp.'),li('Run transitions','Move each fixture through normalization, generation, validation, review and approval/rejection. Preserve the audit trail.'),li('Test discovery','Ask a natural-language query that requires category, attribute and inventory. Mark what may be answered and what must come from an authority.'),li('Inject failure','Remove the inventory response or feed a conflicting supplier update. Record the safe response and reconciliation action.'),li('Accept','Save the state machine, test results and remaining owner questions.')]), expected='A reversible content workflow and discovery contract with source authority, HITL review, authorization and safe failure.', trouble='If the generated answer sounds plausible but has no source or current inventory evidence, classify it as unsafe draft output.')
]


DAY157 = [
    dict(topic_id='048', title='Compare secure modernization of legacy files, ETL, databases and containers',
         overview='<p>Defend a modernization path for Cymbal’s mixed environment. Compare staged coexistence, selective replacement and a broader rewrite using dependency, data freshness, rollback, security, team skills and cost—not a presumed seasonal-traffic or database requirement.</p>',
         technical='''<p>Map the migration by capability: supplier file intake, normalization/ETL, catalog storage, search/discovery, customer interaction, order entry and operations. A file transfer succeeding is not the same as a catalog update being accepted. Keep a reconciliation ledger with source file/version, row counts, checksums, rejected records and downstream publication state.</p><table><caption>Modernization choice points</caption><thead><tr><th>Choice</th><th>Lower-risk use</th><th>Hidden cost</th><th>Acceptance</th></tr></thead><tbody><tr><td>Strangler path</td><td>Preserve legacy contracts while replacing one capability.</td><td>Dual writes, routing and reconciliation.</td><td>Old/new results agree for a declared cohort.</td></tr><tr><td>Batch bridge</td><td>Stable supplier files with tolerable freshness.</td><td>Late files, duplicates and delayed correction.</td><td>Completeness, freshness and replay test.</td></tr><tr><td>Streaming/event path</td><td>Frequent changes with clear event ownership.</td><td>Ordering, duplicates, schema evolution and observability.</td><td>Idempotent replay and contract fixtures.</td></tr><tr><td>Database change</td><td>Only when access pattern, consistency or ownership requires it.</td><td>Migration, compatibility and operational learning.</td><td>Measured workload and rollback evidence.</td></tr></tbody></table>''',
         problem_title='Case 1 · A direct rewrite breaks the file contract that suppliers still use',
         problem='''<p><strong>Situation and impact:</strong> A team replaces an ETL path with a new service and disables the old parser. Supplier files contain a field variation not represented in the new schema; products are silently skipped and search coverage falls.</p><p><strong>Diagnosis and solution:</strong> The migration treated the legacy format as implementation detail rather than an external contract. Keep a compatibility boundary, quarantine invalid rows, measure completeness, run old/new in parallel for a cohort and retain rollback until reconciliation passes.</p><p><strong>Residual risk:</strong> Parallel paths increase operational work. Set an explicit exit condition and owner for retiring the old flow.</p>''',
         lab_title='Compare a coexistence and replacement migration', lab_goal='Create a Cymbal modernization ADR with a reversible wave and data-reconciliation acceptance.',
         steps=''.join([li('Inventory','List file, ETL, database, container, search and order dependencies from Day 156.'),li('Draft paths','Describe a staged coexistence option and a replacement option with ownership and migration sequence.'),li('Define reconciliation','Specify counts, checksums, rejected records, freshness, duplicates and customer-facing acceptance.'),li('Inject a fault','Send a late, duplicate or malformed supplier file; record quarantine, replay and rollback behavior.'),li('Choose','Select using evidence, skills, risk, cost and required freshness; name the condition that reverses the choice.'),li('Save','Record the ADR and wave acceptance in the daily artifact.')]), expected='A migration comparison that names the first failure boundary, reconciliation evidence, rollback point and retirement condition.', trouble='If the design says “migrate the database” without naming application dependencies and rollback, return to the capability map.')
    ,dict(topic_id='048', title='Justify each database, approval, observability and cost choice',
         overview='<p>Database selection is downstream of access patterns, consistency, transaction boundaries, latency, recovery and team ownership. Likewise, observability should connect the catalog journey—not merely add a new dashboard beside Grafana, Nagios and Elastic.</p>',
         technical='''<p>For every existing MySQL, SQL Server, Redis or MongoDB use, write the data model, read/write pattern, transaction need, TTL, scale shape and migration constraint. Do not infer that a distributed database is better without a requirement. For approval and discovery, trace user, associate, service account and supplier identities separately. Centralize useful events while preserving the owner’s ability to diagnose source, derived, review and publication states.</p><p>Cost analysis should include database instances, storage, replication, data transfer, ETL or event processing, search/indexing, model calls, review labor and duplicated coexistence. Record which inputs are measured, supplied or estimated and date current pricing checks.</p><div class="callout"><strong>Review question</strong><p>Can the proposed architecture explain one incorrect catalog item from supplier input to customer response, including who changed it, which version was published and how it is corrected?</p></div>''',
         problem_title='Case 2 · More databases and dashboards create less clarity',
         problem='''<p><strong>Situation and impact:</strong> The modernization adds a new catalog database, cache and observability stack, but teams cannot agree which record is authoritative. A generated attribute is corrected in one store and remains stale in another.</p><p><strong>Diagnosis and solution:</strong> The proposal selected components without defining ownership and data contracts. Choose the smallest set of stores that satisfies the measured access patterns, define cache invalidation and source authority, and emit correlation IDs across file, API, review and publication paths.</p><p><strong>Residual risk:</strong> Central observability can increase retention and ingestion cost. Set sampling, retention and alert ownership intentionally.</p>''',
         lab_title='Build a data-owner and observability decision table', lab_goal='Tie database and monitoring choices to concrete access patterns, owners and acceptance signals.',
         steps=''.join([li('Classify data','For each store identify source/derived/cache data, consistency, retention and owner.'),li('Compare','Write two viable database/runtime combinations and one rejected choice; include migration and cost variables.'),li('Trace a request','Follow a supplier correction through API, database, cache, review and customer read with a correlation ID.'),li('Inject inconsistency','Make the cache or derived store stale. Record detection, invalidation and customer-safe behavior.'),li('Set observability','Choose signals for completeness, freshness, approval backlog, errors, latency, spend and security; assign owners.'),li('Save','Append the decision table and a dated pricing/limit question list.')]), expected='A defensible database and observability matrix grounded in access patterns, ownership, failure behavior and cost.', trouble='If the only justification is “recommended service,” state the workload requirement that makes it fit or mark it unresolved.')
]


DAY158 = [
    dict(topic_id='049', title='Read the official KnightMotives case',
         overview='<p>KnightMotives is an automotive manufacturer moving toward a complete automotive experience. The case describes declining experience in hybrid and ICE vehicles, an unreliable online ordering flow, dealer tooling gaps, largely on-premises IT, an outdated supply-chain mainframe and ERP, fragmented vehicle codebases, plant and rural connectivity challenges, security history, EU privacy concerns and a five-year transformation.</p>',
         technical='''<p>Separate the case’s business outcomes from its technology proposals. The requirements span vehicle UX and connectivity, build-to-order and dealer workflows, hybrid modernization, autonomous-vehicle development and simulation, data monetization, security/incident response, privacy and workforce capability. Draw these as dependent value streams rather than treating “IoT analytics” as the whole problem.</p><table><caption>KnightMotives discovery register</caption><thead><tr><th>Case fact</th><th>Business outcome</th><th>Constraint or dependency</th><th>Question before design</th></tr></thead><tbody><tr><td>Online ordering is unreliable and dealers lack useful data</td><td>Reliable build-to-order and dealer/customer transparency</td><td>Legacy order, ERP and dealer workflows</td><td>Which system owns configuration, price, allocation and order status?</td></tr><tr><td>Plants and rural vehicles have connectivity challenges</td><td>Consistent experience and reliable telemetry</td><td>Intermittent links, bandwidth and offline behavior</td><td>What must work locally when the link is absent?</td></tr><tr><td>Data is siloed and security has suffered breaches</td><td>Safe insight and funding for new capability</td><td>Privacy, segmentation, incident response and consent</td><td>Which data may be monetized, for whom and under what policy?</td></tr><tr><td>Autonomous capability will be targeted in favorable regions</td><td>Safe, compliant research and deployment</td><td>Regulatory variation, simulation and model evidence</td><td>What is the release gate from simulation to road testing?</td></tr></tbody></table>''',
         problem_title='Case 1 · A cloud-first roadmap ignores dealer, plant and vehicle boundaries',
         problem='''<p><strong>Situation and impact:</strong> The transformation proposal moves customer and manufacturing workflows to cloud services but assumes dealers can replace equipment and plants have stable connectivity. Ordering, service and telemetry fail during a link outage and the business cannot explain which side owns a change.</p><p><strong>Diagnosis and solution:</strong> The design started with destination products instead of dependency and availability boundaries. Preserve explicit local/offline behavior, phase dealer tooling, inventory network capacity, define ownership and reconcile writes before surfacing a status.</p><p><strong>Residual risk:</strong> The case does not supply every latency, capacity, regulatory or funding number. Keep these as discovery questions and do not present them as requirements.</p>''',
         lab_title='Extract KnightMotives facts and dependencies', lab_goal='Produce a source-linked dependency map and prioritized business-outcome register.',
         steps=''.join([li('Read and cite','Create <code>day-158-knightmotives-facts.md</code>; cite the official case page for each statement.'),li('List outcomes','Record customer, dealer, manufacturing, vehicle, safety, data and workforce outcomes without choosing products.'),li('Map dependencies','Connect online ordering, dealer tools, mainframe/ERP, plants, rural vehicles, analytics, simulation, identity and incident response.'),li('Mark boundaries','Label cloud, on-premises, vehicle, plant, dealer, regional regulatory and data-owner boundaries.'),li('Prioritize','Rank outcomes by customer impact, safety, regulatory exposure, dependency and evidence readiness.'),li('Close out','Save the map and unresolved-question list; link both from the exit artifact.')]), expected='A source-linked dependency map that makes offline, dealer, legacy, privacy, security and skills constraints visible.', trouble='If a requirement is actually a proposed solution, move it to the inference column and write the question that would confirm it.')
    ,dict(topic_id='049', title='Identify ordering, dealer, legacy-system, connectivity, AI, privacy and skills constraints',
         overview='<p>The architecture must support adoption as well as technology. Dealer resources, plant operations, vehicle software compatibility, security response, EU privacy and workforce readiness can change the sequence more than a service feature can.</p>',
         technical='''<p>Use a bounded context for vehicle and dealer data. Order state needs a clear owner, idempotency and reconciliation. Vehicle and plant paths need a declared offline queue, retry policy and safe local behavior. Data monetization needs classification, consent or lawful-use decisions, de-identification where appropriate, access controls and an exit path when policy changes. AI/simulation work needs separate research, evaluation, safety and production release boundaries.</p><p>Skills and funding are architecture constraints: a design requiring new platform, data, security and embedded expertise on every team is not a five-year plan without an adoption wave. Define a thin first capability, a training/ownership plan, measurable value and a rollback or pause point.</p><div class="callout"><strong>Decision rule</strong><p>Prefer the wave that reduces a declared customer or safety risk while preserving the ability to stop, reconcile and learn. Do not monetize data merely because it exists.</p></div>''',
         problem_title='Case 2 · Data monetization outruns privacy and incident readiness',
         problem='''<p><strong>Situation and impact:</strong> A business unit publishes aggregated driving data to fund the transformation. The pipeline cannot show consent, regional handling, deletion, access or breach response. A security incident now affects trust and funding at once.</p><p><strong>Diagnosis and solution:</strong> Data value was prioritized before classification, purpose, access and response. Create a data product contract, policy gate, regional controls, audit trail, incident playbook and revocation/deletion path. Treat monetization as an opt-in product with a defined owner.</p><p><strong>Residual risk:</strong> De-identification is not a universal guarantee. Validate re-identification risk and legal interpretation with the responsible experts.</p>''',
         lab_title='Turn constraints into a first modernization wave', lab_goal='Convert the discovery register into an ordered wave with privacy, skills and adoption gates.',
         steps=''.join([li('Choose a capability','Select ordering, dealer service, plant connectivity, data platform or simulation as the first bounded wave.'),li('Define the boundary','Name source of truth, offline behavior, identities, data class, region and affected teams.'),li('Set gates','Add security, privacy, reliability, adoption, cost and rollback acceptance.'),li('Model a stop','Stop the wave after a link outage, data-policy change, dealer rejection or migration mismatch. Record safe behavior.'),li('Plan enablement','Add training, support, owner and funding assumptions; label all estimates.'),li('Save','Write the prioritized wave and its evidence plan into the exit artifact.')]), expected='A bounded first wave with explicit data and operational boundaries, adoption owner, pause trigger and residual risk.', trouble='If the first wave requires every legacy system to change, shrink it until a reversible user or operator outcome is testable.')
]


DAY159 = [
    dict(topic_id='049', title='Compare hybrid modernization, dealer tooling, protected data and AI options',
         overview='<p>Defend a phased KnightMotives design rather than a single platform diagram. Compare options for hybrid integration, dealer experience, data products, AI/simulation and rollout using the Day 158 dependency map.</p>',
         technical='''<p>Use waves with explicit entry and exit criteria: establish identity, network and data boundaries; stabilize ordering and dealer visibility; modernize selected legacy interfaces; build governed data products; then expand AI and simulation. Preserve an anti-corruption or compatibility layer around the mainframe/ERP until the replacement proves business and reconciliation behavior.</p><table><caption>KnightMotives defense matrix</caption><thead><tr><th>Wave</th><th>Primary value</th><th>Failure containment</th><th>Exit evidence</th></tr></thead><tbody><tr><td>Order and dealer status</td><td>Reliable build-to-order and transparency</td><td>Coexistence, idempotent commands, manual fallback</td><td>Reconciled order/status cohort and dealer acceptance</td></tr><tr><td>Hybrid connectivity</td><td>Plant and headquarters data movement</td><td>Dual path, local queue, backpressure and clear owner</td><td>Failure/recovery trace and capacity evidence</td></tr><tr><td>Governed data product</td><td>Safe insight or monetization</td><td>Classification, policy, consent, access and revocation</td><td>Lineage, audit and approved use case</td></tr><tr><td>AI/simulation</td><td>Research and future experience</td><td>Sandbox, evaluation, regional gate and human safety review</td><td>Reproducible evaluation and release decision</td></tr></tbody></table>''',
         problem_title='Case 1 · A big-bang transformation loses the ability to roll back',
         problem='''<p><strong>Situation and impact:</strong> A single release changes ordering, dealer tools, ERP integration and analytics. A defect in one contract blocks dealer operations and makes it impossible to distinguish an application bug from a data or network failure.</p><p><strong>Diagnosis and solution:</strong> The design coupled independent boundaries and had no cohort, feature flag, reconciliation or wave owner. Sequence the work, preserve old/new comparison, route a small cohort, define rollback authority and make every write idempotent.</p><p><strong>Residual risk:</strong> Parallel operations cost money and attention. Set a time-bound retirement decision for each compatibility layer.</p>''',
         lab_title='Sequence a phased modernization with a stopped wave', lab_goal='Produce a phased design that remains safe when one wave is halted or a dealer cannot adopt it.',
         steps=''.join([li('Select waves','Use Day 158 outcomes to order identity/network, ordering/dealer, data, and AI/simulation work.'),li('Define contracts','For each wave specify API/file/event contract, source of truth, cohort, owner and rollback.'),li('Stop one wave','Make a dealer reject the new tool, a plant link unavailable or a reconciliation check fail.'),li('Recover','Route to the old path or manual fallback; record data repair, customer communication and evidence.'),li('Review cost','Include duplicate operation, support, training, connectivity and storage cost assumptions.'),li('Defend','Write the choice, rejected alternative and condition to change it; save the phased ADR.')]), expected='A wave plan with reversible boundaries, adoption evidence, stopped-wave behavior, funding assumptions and owner.', trouble='If rollback only means redeploying code, check whether data, dealer actions or vehicle state also need reconciliation.')
    ,dict(topic_id='049', title='Justify telemetry and simulation services as options, not the whole case',
         overview='<p>Telemetry, simulation and analytics support the transformation but do not replace ordering, dealer, legacy, privacy, security and adoption work. Keep operational signals and research data flows separate enough to protect the business path.</p>',
         technical='''<p>Define telemetry at the producer, gateway, transport, ingestion, storage, processing and consumer boundaries. Rural or vehicle connectivity may be intermittent, so buffer, timestamp, deduplicate and declare what data is lost or delayed. Simulation data needs provenance, scenario version, model version and a gate before it informs a safety or product decision. Monitor data quality and security, not only throughput.</p><p>Protected data products should expose only an approved contract. Make access, purpose, region, retention, deletion and incident response observable. A telemetry service is useful only when its signals change a decision—capacity, safety, reliability, customer support or release readiness.</p><div class="callout"><strong>Review question</strong><p>What is the smallest signal that would tell the team a vehicle, plant, dealer or order is unsafe or stuck, and what action follows?</p></div>''',
         problem_title='Case 2 · Telemetry is abundant but no owner can act on it',
         problem='''<p><strong>Situation and impact:</strong> Millions of events enter an analytics platform, but timestamps, vehicle/software versions and consent metadata are incomplete. Operations see dashboards while dealers and safety teams cannot identify an affected cohort.</p><p><strong>Diagnosis and solution:</strong> The design measured ingestion, not decision quality. Define event contracts, identity/version fields, freshness and completeness checks, ownership and alert actions. Quarantine unusable data and preserve a replay path.</p><p><strong>Residual risk:</strong> More telemetry increases storage, network and privacy exposure. Retain only what has an owner and declared purpose.</p>''',
         lab_title='Design an actionable telemetry and simulation contract', lab_goal='Create synthetic event contracts and a release gate that connect data quality to an operational decision.',
         steps=''.join([li('Define events','Write fields for vehicle/plant/dealer identity, software version, time, region, consent/purpose and sequence.'),li('Define states','Set accepted, delayed, duplicate, rejected and quarantined states with owners.'),li('Model an outage','Drop connectivity and replay events out of order. Record local behavior, deduplication and recovery.'),li('Add simulation gate','Name scenario/model versions, evaluation evidence and who approves movement toward production.'),li('Choose signals','Set completeness, freshness, duplicate, security and action metrics; connect each to a runbook.'),li('Save','Append the contract and release gate to the Day 159 artifact.')]), expected='A telemetry/simulation contract with offline, replay, privacy, evaluation and action ownership made explicit.', trouble='If the signal cannot trigger an action or a safe fallback, it is not yet an operational requirement.')
]


DAY160 = [
    dict(topic_id='063', title='Review the four case packages for traceability, cost and failure behavior',
         overview='<p>Use EHR, Altostrat, Cymbal and KnightMotives as a portfolio of reasoning patterns. Audit the existing packages for requirement traceability, unsupported assumptions, failure behavior, cost ownership and evidence quality. Repair the weakest package; do not rewrite all four.</p>',
         technical='''<p>A strong case package has a chain: supplied fact → requirement → decision → rejected alternative → acceptance signal → failure response → owner. Review all four cases with the same rubric, then compare whether a decision that was valid in one context was incorrectly transferred to another. Case-study questions reward the option that meets the stated requirement with the least unnecessary operational burden, not the most elaborate architecture.</p><table><caption>Portfolio audit rubric</caption><thead><tr><th>Check</th><th>Pass evidence</th><th>Common defect</th></tr></thead><tbody><tr><td>Facts</td><td>Source/page or prior artifact is named.</td><td>Proposed service presented as case fact.</td></tr><tr><td>Requirements</td><td>Business and technical acceptance are measurable or open questions.</td><td>“Scalable” or “secure” with no signal.</td></tr><tr><td>Trade-offs</td><td>One credible alternative and revisit condition.</td><td>One preferred product with no rejected option.</td></tr><tr><td>Failure</td><td>First failing boundary, safe response and owner.</td><td>Diagram treated as proof of recovery.</td></tr><tr><td>Cost/operations</td><td>Drivers, skills, toil and current-verification items are visible.</td><td>Cost or support burden ignored.</td></tr></tbody></table>''',
         problem_title='Case · Four polished packages contain the same unsupported assumption',
         problem='''<p><strong>Situation and impact:</strong> The portfolio says managed services reduce operations, AI outputs are safe, a regional design meets recovery, and a migration is reversible. None of the packages names the acceptance evidence or the owner. The learner memorizes conclusions that fail when a constraint changes.</p><p><strong>Diagnosis and solution:</strong> The packages were reviewed for vocabulary instead of reasoning. Apply the common rubric, label claim confidence, repair one causal chain and transfer the correction to the capstone evidence index.</p><p><strong>Residual risk:</strong> A corrected artifact improves reasoning but does not predict an exam score or production outcome.</p>''',
         lab_title='Audit and repair the weakest case package', lab_goal='Produce a corrected case portfolio and evidence-based error log.',
         steps=''.join([li('Choose the weak package','Score each case on facts, requirements, alternatives, failure, cost and evidence; select the lowest score.'),li('Trace five claims','For each claim record source, type, owner, decision, signal and unresolved question.'),li('Inject a constraint','Change cost, residency, recovery, connectivity or skills. Mark the first affected decision.'),li('Repair','Rewrite one ADR section, acceptance test and failure response; preserve the rejected alternative.'),li('Transfer','Add the reusable reasoning rule to the matching capstone or exam error log.'),li('Save','Record before/after scores and remaining uncertainty.')]), expected='A corrected weakest package, a common rubric score and an error log that distinguishes knowledge, reading and evidence problems.', trouble='If every package scores equally, use missing acceptance evidence and unsupported assumptions as tie-breakers.')
]


DAY161 = [
    dict(topic_id='063', title='Choose one fictional scenario and defend it under a changed constraint',
         overview='<p>Practice architecture reasoning without relying on a memorized case. Choose one scenario—retail, healthcare, payments, gaming, media, IoT, government, SaaS or manufacturing—define the initial requirement set, then change one cost, residency or recovery constraint.</p>',
         technical='''<p>Time-box the first design. Write the business outcome, workload shape, state owner, data location, identity, SLO or recovery target, cost boundary and team capability. Select the minimum viable architecture and name an alternative. When a constraint changes, revisit all six Well-Architected lenses: operational excellence, security, reliability, performance, cost and sustainability.</p><table><caption>Changed-constraint review</caption><thead><tr><th>Lens</th><th>Initial answer</th><th>Changed constraint question</th><th>Required evidence</th></tr></thead><tbody><tr><td>Reliability</td><td>Declared failure domains and recovery path</td><td>What changes when RTO/RPO tightens?</td><td>Failover/restore sequence and owner.</td></tr><tr><td>Security</td><td>Identity, data and network boundaries</td><td>What changes when residency or access changes?</td><td>Policy/access evidence and audit owner.</td></tr><tr><td>Cost</td><td>Unit drivers and budget boundary</td><td>What must be removed or deferred?</td><td>Sensitivity and service/feature trade-off.</td></tr><tr><td>Operations</td><td>Skills and support model</td><td>Can the team run the new design?</td><td>Toil, training and escalation plan.</td></tr></tbody></table>''',
         problem_title='Case · A design survives one lens and fails the changed constraint',
         problem='''<p><strong>Situation and impact:</strong> A design meets the latency target but violates the new residency requirement and doubles the operating cost. The architect changes storage and networking without revisiting identity, recovery, support or sustainability.</p><p><strong>Diagnosis and solution:</strong> The decision was optimized as a single metric. Re-run the full lens review, identify the first requirement conflict, choose what to preserve, and document a phased alternative rather than hiding the trade-off.</p><p><strong>Residual risk:</strong> Fictional scenarios train method, not product mastery. Mark all product limits and prices for later verification.</p>''',
         lab_title='Run the 30-minute before/after ADR', lab_goal='Defend one fictional architecture, change one constraint and record the complete six-lens response.',
         steps=''.join([li('Choose scope','Write a one-paragraph scenario and five measurable requirements; avoid adding unnecessary services.'),li('Draft quickly','In 10 minutes draw the data, identity, runtime and failure boundaries; choose an option and reject one alternative.'),li('Change one constraint','Use a cost cut, region/residency change or stricter recovery target.'),li('Recalculate','Update affected data flow, security, reliability, performance, cost, sustainability and operations decisions.'),li('Defend','In five minutes state what stays, what changes, why, evidence needed and residual risk.'),li('Save','Store the before/after ADR and six-pillar critique.')]), expected='A concise before/after ADR where the changed constraint changes explicit decisions and not just the diagram label.', trouble='If the new constraint changes nothing, it is either not material or the initial design did not state its assumptions.')
]


DAY162 = [
    dict(topic_id='050', title='Read the current standard-exam guide and distinguish renewal scope',
         overview='<p>Map the current standard Professional Cloud Architect exam domains to your evidence. The official certification page distinguishes the standard and renewal paths; this day focuses on the standard exam unless the learner explicitly needs renewal preparation.</p>',
         technical='''<p>The current standard guide organizes the exam around six domains: designing and planning a cloud solution architecture; managing and provisioning infrastructure; designing for security and compliance; analyzing and optimizing technical and business processes; managing implementation; and ensuring solution and operations excellence. The guide gives approximate weights, but the practical task is to connect each domain to evidence and decision rules rather than memorize percentages.</p><table><caption>Exam-domain evidence map</caption><thead><tr><th>Domain</th><th>Evidence to map</th><th>Repair signal</th></tr></thead><tbody><tr><td>Design and plan</td><td>Requirements, ADRs, migrations, diagrams and cost trade-offs.</td><td>Can name products but cannot explain why.</td></tr><tr><td>Manage/provision</td><td>IAM, networking, storage, compute, orchestration and automation artifacts.</td><td>Cannot identify owner or provisioning boundary.</td></tr><tr><td>Security/compliance</td><td>Identity, keys, policy, audit, data classification and AI safeguards.</td><td>Confuses encryption with authorization or audit.</td></tr><tr><td>Optimize processes</td><td>Incident, cost, capacity, stakeholder and business-success evidence.</td><td>Chooses a technical fix without business signal.</td></tr><tr><td>Manage implementation</td><td>CI/CD, testing, migration, APIs, Terraform and tool evidence.</td><td>Cannot state rollout or rollback proof.</td></tr><tr><td>Operations excellence</td><td>SLOs, observability, recovery, release and reliability experiments.</td><td>Uses a dashboard or topology as proof of resilience.</td></tr></tbody></table><p>Renewal has a different scope and format. Read the current certification page and guide before deciding which path applies; do not infer eligibility from a practice score.</p>''',
         problem_title='Case 1 · A learner studies the wrong exam scope',
         problem='''<p><strong>Situation and impact:</strong> A learner prepares only generative-AI case questions while planning to take the standard exam, or studies standard breadth while actually eligible for renewal. Time is spent on the wrong evidence and score interpretation.</p><p><strong>Diagnosis and solution:</strong> The exam path was not confirmed from the official source. Record exam type, current guide, domain map, date checked and preparation source before scheduling study blocks.</p><p><strong>Residual risk:</strong> Certification rules, formats and product terminology can change. Recheck official pages close to registration.</p>''',
         lab_title='Build the six-domain evidence map', lab_goal='Map existing artifacts to the current standard guide and identify the weakest domain.',
         steps=''.join([li('Confirm scope','Open the official certification page and standard guide; record standard versus renewal and the date checked.'),li('Map evidence','For each domain list at least two existing artifacts and one decision rule you can defend.'),li('Score confidence','Use New, Familiar or Demonstrated; cite the artifact rather than self-rating alone.'),li('Find the gap','Choose the weakest domain by missing evidence or inability to explain a trade-off.'),li('Plan repair','Write a small corrective exercise and a source link; do not add unrelated scope.'),li('Save','Export the dated domain map and remediation list.')]), expected='A source-dated six-domain map with evidence links, confidence labels and a prioritized repair plan.', trouble='A completed page is not evidence of competence; point to a reproducible artifact or mark the topic Familiar.')
    ,dict(topic_id='071', title='Record why sample-question answers fail the stated requirements',
         overview='<p>Use official sample questions or legitimate practice material as reasoning exercises. For every incorrect or uncertain answer, record the requirement you missed, the distractor’s hidden violation, the evidence that would decide the choice and the rule you will reuse.</p>',
         technical='''<p>Question analysis is not just answer memorization. Parse the actor, workload, state, constraint, desired outcome, operational overhead and “must not” clause. Eliminate options that violate a hard requirement before comparing soft trade-offs. When two options remain, prefer the one that meets the requirement with less unnecessary operational burden and fewer unverified assumptions.</p><div class="callout"><strong>Error taxonomy</strong><p>Tag each miss as <code>knowledge gap</code>, <code>requirements misread</code>, <code>scope/wording trap</code>, <code>calculation</code>, <code>time pressure</code> or <code>unsupported assumption</code>. Each tag gets a different repair.</p></div>''',
         problem_title='Case 2 · A score improves while the reasoning remains unrepeatable',
         problem='''<p><strong>Situation and impact:</strong> A learner remembers that one product was correct in a similar question but cannot state the requirement or why the alternatives fail. New wording or a changed region/cost constraint causes the same error.</p><p><strong>Diagnosis and solution:</strong> The study log captured answer letters instead of causal reasoning. Rewrite misses with requirement, eliminated options, evidence and a changed-constraint check.</p><p><strong>Residual risk:</strong> Practice content may not match the live exam. Use it to train reasoning, not to infer question leakage or readiness.</p>''',
         lab_title='Analyze a sample-question error', lab_goal='Turn one wrong or uncertain answer into a reusable decision rule and remediation task.',
         steps=''.join([li('Copy the question safely','Record source, date and a short paraphrase; do not collect unauthorized exam content.'),li('Extract constraints','List actor, data, latency, availability, cost, security, operations and forbidden changes.'),li('Eliminate','For each distractor write the exact requirement it violates or the assumption it introduces.'),li('Decide','State why the selected answer is sufficient and what evidence would reverse it.'),li('Change a constraint','Alter one requirement and see whether the answer changes.'),li('Log','Save the error taxonomy, rule, source and follow-up exercise.')]), expected='An error log entry that explains the requirement, elimination logic, decision rule and repair source.', trouble='If the explanation says only “this is best practice,” add the specific requirement and operational consequence.')
]


DAY163 = [
    dict(topic_id='050', title='Build flash cards for service limits, decision rules and SLAs',
         overview='<p>Build compact, source-backed prompts for facts that are easy to misremember: service limits, SLA conditions, scopes, regional behavior, quotas, delivery guarantees and decision rules. A flash card must include the source date and the condition that makes the fact applicable.</p>',
         technical='''<p>Do not memorize a bare number. A useful card has service, limit or behavior, scope, unit, condition, source URL/date and what to do when the limit is reached. Separate documented behavior from a local observation and from a design assumption. For SLAs, record eligibility, exclusions, measurement window and service combination; never generalize a percentage across products.</p><div class="callout"><strong>Card format</strong><p><code>Question | answer with unit/scope | condition | source/date | design consequence | verification command or page</code>. Delete stale cards when the source changes.</p></div>''',
         problem_title='Case 1 · A memorized limit is applied outside its scope',
         problem='''<p><strong>Situation and impact:</strong> An architect recalls a quota or SLA number but not its region, resource type, eligibility or measurement condition. The design promises capacity or availability that the service documentation does not support.</p><p><strong>Diagnosis and solution:</strong> The card omitted scope and source date. Replace it with a conditional card and record the design action when the limit is reached: request increase, shard, queue, reserve, degrade or choose another service.</p><p><strong>Residual risk:</strong> Current docs remain authoritative; cards are review aids, not evidence by themselves.</p>''',
         lab_title='Create a source-backed limit deck', lab_goal='Create and audit a small set of conditional flash cards from official documentation and prior artifacts.',
         steps=''.join([li('Choose facts','Select five limits/SLAs/guarantees that affect your repaired case or weakest domain.'),li('Verify','Open the current official page and record scope, unit, condition, exclusions and date.'),li('Write cards','Use the full card format and include the consequence for architecture.'),li('Cross-check','Find one card whose answer changes under a region, scale or workload condition.'),li('Rehearse','Answer without the source, then verify; mark uncertainty rather than guessing.'),li('Save','Store the deck and a stale-source review date in the exit artifact.')]), expected='A small, dated deck of conditional facts with official links and design consequences.', trouble='If a card has no condition or source date, it is a slogan; rewrite it before keeping it.')
    ,dict(topic_id='050', title='Practise elimination',
         overview='<p>Use elimination to remove options that violate hard requirements before comparing the survivors. The goal is not to guess a product from a keyword; it is to prove why an option cannot satisfy the stated boundary.</p>',
         technical='''<p>Mark each option against hard constraints first: identity, data location, connectivity, recovery, managed-versus-self-managed requirement, no-code-change requirement, ordering, latency or cost. Then compare remaining options on operational burden and evidence. Record the exact clause that eliminated each option; a vague “not recommended” is not enough.</p>''',
         problem_title='Case 2 · The most familiar service survives because no option was eliminated explicitly',
         problem='''<p><strong>Situation and impact:</strong> A learner selects a familiar runtime even though the question requires a different network boundary or minimal operations. The reasoning never tests the hard constraint.</p><p><strong>Diagnosis and solution:</strong> Start with a constraint table and eliminate violations before feature comparison. Keep a final alternative and revisit condition.</p><p><strong>Residual risk:</strong> Multiple answers may be technically feasible; use the question’s exact priority and operational context.</p>''',
         lab_title='Run an elimination drill', lab_goal='Analyze a small set of legitimate practice questions using requirement-first elimination.',
         steps=''.join([li('Set the timer','Use a short, fixed window and record start/end times.'),li('Underline constraints','Mark must, least, lowest, without changing code, global, near-real-time and operational-overhead phrases.'),li('Eliminate','Write one disqualifying reason per rejected option.'),li('Compare','For survivors state the deciding trade-off and rejected alternative.'),li('Review','Classify misses as knowledge, wording, calculation or assumption.'),li('Save','Add the drill results to the error log.')]), expected='A reasoning log where every eliminated option fails a named requirement and the selection fits the requested priority.', trouble='If every option survives, identify the hidden scope or missing assumption instead of choosing by familiarity.')
    ,dict(topic_id='050', title='Watch for keywords without treating them as automatic answers',
         overview='<p>Keywords compress a requirement but do not choose the service alone. Translate them into a testable decision: “minimum operational overhead” changes the ownership boundary; “lowest cost” requires workload and lifecycle assumptions; “global” still needs data and failure-domain analysis.</p>',
         technical='''<p>Create a two-column habit: keyword/phrase and the requirement it signals. Then write the counter-question. “Least privilege” asks which principal and resource; “without changing code” asks what compatibility boundary exists; “near real time” asks latency, freshness and event semantics; “global” asks write ownership, routing, residency and failover. Keywords narrow the search space; they do not replace the case facts.</p>''',
         problem_title='Case 3 · Keyword matching chooses a globally named service that violates residency',
         problem='''<p><strong>Situation and impact:</strong> A learner sees “global” and selects a globally scoped design, missing that data must remain in a region and writes have one owner. The answer satisfies a word but fails the full requirement.</p><p><strong>Diagnosis and solution:</strong> Translate the keyword into a decision checklist and test the data, identity, failure and compliance consequences. Prefer the narrowest option that satisfies the entire statement.</p><p><strong>Residual risk:</strong> Keyword drills must be followed by full case reading; they are not a substitute for requirements analysis.</p>''',
         lab_title='Build a keyword-to-requirement worksheet', lab_goal='Turn common exam phrases into counter-questions and evidence checks.',
         steps=''.join([li('Collect phrases','Use prior error logs and the official guide; avoid copying protected exam content.'),li('Translate','For each phrase write the requirement, hidden boundary and counter-question.'),li('Test','Apply three phrases to one existing case package and see whether the chosen option still fits.'),li('Add traps','Record one example where the keyword alone would lead to the wrong answer.'),li('Review','Ask a peer or future self what evidence would change the choice.'),li('Save','Store the worksheet with the domain map.')]), expected='A keyword worksheet that prompts complete requirement checks and documents common traps.', trouble='If the phrase maps to a product name instead of a requirement, rewrite it as an actor, boundary, outcome or constraint.')
    ,dict(topic_id='050', title='Time management drills for a long exam',
         overview='<p>Practise pacing as a reasoning control. Record time per question, flag uncertainty, move on when a question is consuming disproportionate time, and return only when the remaining evidence justifies it. Do not convert a timed drill into a readiness claim.</p>',
         technical='''<p>Use a three-pass approach: first answer clear items, second resolve questions requiring a short calculation or elimination, third review flagged items and select an answer. Preserve a one-line reason for each flag so the review is targeted. Track whether time loss came from reading, indecision, arithmetic, product recall or over-analysis.</p>''',
         problem_title='Case 4 · Over-analysis turns a knowledge gap into a timing failure',
         problem='''<p><strong>Situation and impact:</strong> A learner spends several minutes proving an answer to one ambiguous question, then guesses later questions without reading their constraints.</p><p><strong>Diagnosis and solution:</strong> The process had no stop rule or error taxonomy. Use a first-pass decision, flag uncertainty, record the missing fact and continue; remediate the fact after the timed set.</p><p><strong>Residual risk:</strong> Practice timing is sensitive to environment and content mix. Track trends over multiple legitimate sets.</p>''',
         lab_title='Run a timed reasoning set and analyze pacing', lab_goal='Complete a legitimate timed set, justify eliminations and separate timing from knowledge errors.',
         steps=''.join([li('Prepare','Choose a legitimate practice set, timer and answer log; record source and conditions.'),li('Pass one','Answer clear questions, flag uncertain ones and write a short reason without researching.'),li('Pass two','Return to flags, verify the requirement and complete the decision.'),li('Classify','For every miss or slow item tag knowledge, misread, calculation, assumption or timing.'),li('Repair','Choose one corrective source or exercise for each repeated error class.'),li('Save','Record score only as a local signal, alongside the error log and next review date.')]), expected='A timed error log with per-question reasoning, pacing data, error categories and targeted next actions.', trouble='If the score is high but the error log is empty, the drill did not capture enough reasoning to guide repair.')
]


SOURCE_155 = '<a href="../sources.html#topic-047">Topic 047 source section</a> and the <a href="https://services.google.com/fh/files/misc/v6.1_pca_altostrat_media_case_study_english.pdf" rel="noopener noreferrer">official Altostrat Media case</a>.'
SOURCE_156 = '<a href="../sources.html#topic-048">Topic 048 source section</a> and the <a href="https://services.google.com/fh/files/misc/v6.1_pca_cymbal_retail_case_study_english.pdf" rel="noopener noreferrer">official Cymbal Retail case</a>.'
SOURCE_158 = '<a href="../sources.html#topic-049">Topic 049 source section</a> and the <a href="https://services.google.com/fh/files/misc/v6.1_pca_knightmotives_automotive_case_study_english.pdf" rel="noopener noreferrer">official KnightMotives Automotive case</a>.'
SOURCE_EXAM = '<a href="../sources.html#topic-050">Topic 050 source section</a>; compare the <a href="https://services.google.com/fh/files/misc/professional_cloud_architect_exam_guide_english.pdf" rel="noopener noreferrer">official standard exam guide</a> with the current <a href="https://cloud.google.com/learn/certification/cloud-architect" rel="noopener noreferrer">certification page</a>.'
SOURCE_SYNTH = '<a href="../sources.html#topic-063">Topic 063 source section</a> and the <a href="https://docs.cloud.google.com/architecture" rel="noopener noreferrer">Google Cloud Architecture Center</a>; keep case facts tied to the official case sources.'


def run():
    specs = {
        155: ('Altostrat Media — architecture defense', 'Compare two content/AI integration options using the earlier requirements, retrieval evaluation and delivery evidence.', '<a href="day-154.html">Day 154</a>; bring the Altostrat requirements matrix.', 'An ADR covering quality, auditability, hybrid operations and cost with one rejected option.', DAY155, SOURCE_155),
        156: ('Cymbal Retail — catalog and commerce requirements', 'Read the official case and identify supplier integration, generated content, product discovery and human-review needs.', '<a href="day-155.html">Day 155</a>, <a href="day-139.html">Day 139</a>; bring their exit artifacts.', 'A fact register and content approval/data-flow diagram with security boundaries.', DAY156, SOURCE_156),
        157: ('Cymbal Retail — architecture defense', 'Design a review-before-publication path and conversational discovery flow; test a failure or rejection using synthetic content.', '<a href="day-156.html">Day 156</a>; bring the Cymbal fact register.', 'A one-page design with quality/approval acceptance criteria, integration alternatives and cost assumptions.', DAY157, SOURCE_156),
        158: ('KnightMotives — modernization requirements', 'Extract ordering, dealer, legacy-system, connectivity, AI, privacy and skills constraints from the official case.', '<a href="day-157.html">Day 157</a>, <a href="day-077.html">Day 77</a>; bring their exit artifacts.', 'A source-linked dependency map and prioritized business outcomes.', DAY158, SOURCE_158),
        159: ('KnightMotives — architecture defense', 'Sequence modernization waves and compare connectivity/data/AI options while handling a stopped wave and limited dealer resources.', '<a href="day-158.html">Day 158</a>; bring the KnightMotives dependency map.', 'A phased design with rollback, funding, privacy and adoption risks linked to case facts.', DAY159, SOURCE_158),
        160: ('Case synthesis and feedback', 'Review the four case packages for contradictions and unsupported assumptions; revise the weakest design and transfer findings into the capstones.', '<a href="day-159.html">Day 159</a>; bring all four case packages.', 'A corrected case portfolio and an evidence-based error log for exam review.', DAY160, SOURCE_SYNTH),
        161: ('Changed-constraint design exercise', 'Choose one fictional scenario, defend a design in 30 minutes, then change one cost, residency or recovery constraint and review all six lenses.', '<a href="day-160.html">Day 160</a>; bring the corrected portfolio.', 'A before/after ADR and six-pillar critique.', DAY161, SOURCE_SYNTH),
        162: ('Exam domain mapping and sample questions', 'Map evidence to all six current standard-exam domains, answer official sample questions and analyze every error.', '<a href="day-161.html">Day 161</a>, <a href="day-032.html">Day 32</a>; bring their exit artifacts.', 'A source-dated exam map and remediation list; a sample score is not proof of readiness.', DAY162, SOURCE_EXAM, 'local exercise'),
        163: ('Timed reasoning and source-backed limits', 'Complete a timed set of legitimate practice questions; justify eliminations and verify uncertain limits in current documentation.', '<a href="day-162.html">Day 162</a>; bring the domain map and remediation list.', 'An error log separating knowledge gaps, misread requirements and timing issues, with corrective study links.', DAY163, SOURCE_EXAM, 'local exercise'),
    }
    for number, spec in specs.items():
        title, outcome, prerequisites, exit_artifact, data, source, *mode = spec
        write_page(number, make_day(number, title, outcome, prerequisites, exit_artifact, data, source, mode[0] if mode else 'tabletop / design'))


if __name__ == '__main__':
    run()
